#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <errno.h>

#include "platform.h"
#include "mecha.h"
#include "eeprom.h"
#include "elect.h"
#include "main.h"

extern unsigned char ConMD, ConType, ConTM, ConCEXDEX, ConOP, ConLens, ConChecksumStat;
unsigned char ElectConIsT10K;

static u16 DiscDetectValue136, DVDmaxCalc, CDminCalc, DVDmax, DVDmin;
static unsigned char DisableDVDDLAdjWorkaround, DisableEEPMIRRWrite, Enable2ndJitter256Check;
static unsigned int ConFocusOffset;
static float CDstudy, DVDRatio;

typedef struct ElectMechaTaskPrep
{
    unsigned char id, tag;
    unsigned short int timeout;
    unsigned short int command;
    const char *label;
    const char *args;
} ElectMechaTaskPrep_t;

static const ElectMechaTaskPrep_t AutoAdjACommands[]   = { // Test CD SCD-2700/YEDS-18, DVD-SL HX-504, DVD-DL HX-505
    {1, 0, 1000, MECHA_CMD_DISC_MODE_CD_12, "DISC MODE CD 12cm", NULL},
    {2, 0, 3000, MECHA_CMD_FOCUS_UPDOWN, "FOCUS UP/DOWN END", "00"},
    {3, 0, 3000, MECHA_CMD_SLED_POS_HOME, "CD SLED HOME POSITION", NULL},
    {4, 0, 6000, MECHA_CMD_TRAY, "CD TRAY CLOSE", "00"},
    {5, 0, 6000, MECHA_CMD_TRAY, "CD START (TRAY OPEN)", "01"},
    {0, 0, 0, MECHA_TASK_UI_CMD_MSG, "Insert test CD and press ENTER", NULL},
    {6, 0, 6000, MECHA_CMD_TRAY, "CD TRAY CLOSE", "00"},
    {7, 0, 3000, MECHA_CMD_SLED_POS_HOME, "CD SLED HOME POSITION", NULL},
    {8, 0, 15000, MECHA_CMD_DETECT_ADJ, "CD DETECT ADJUSTMENT", "00"},
    {9, MECHA_CMD_TAG_ELECT_CD_TYPE, 1000, MECHA_CMD_DISC_MODE_CD_8, "CD 8cm DISC MODE", NULL}, // Change to the 12cm YEDS-18 for DTL-T10000/H
    {10, 0, 20000, MECHA_CMD_AUTO_ADJ_ST_1, "CD AUTO ADJUSTMENT (STAGE 1)", "01"},
    {11, 0, 20000, MECHA_CMD_AUTO_ADJ_ST_2, "CD AUTO ADJUSTMENT (STAGE 2)", "01"},
    {12, MECHA_CMD_TAG_ELECT_CD_FE_LOOP_GAIN, 3000, MECHA_CMD_GAIN, "CD GET FE LOOP GAIN", "13"},
    {13, MECHA_CMD_TAG_ELECT_CD_TE_LOOP_GAIN, 3000, MECHA_CMD_GAIN, "CD GET TE LOOP GAIN", "23"},
    {14, 0, 3000, MECHA_CMD_FOCUS_UPDOWN, "CD STOP", "00"},
    {0, 0, 1000, MECHA_TASK_UI_CMD_WAIT, "CD WAIT 1s", NULL},
    {15, 0, 3000, MECHA_CMD_SLED_POS_HOME, "CD SLED HOME POSITION", NULL},
    {16, 0, 6000, MECHA_CMD_TRAY, "CD FIN (TRAY OPEN)", "01"},
    {0, 0, 0, MECHA_TASK_UI_CMD_MSG, "Insert test DVD-SL and press ENTER", NULL},
    {17, 0, 6000, MECHA_CMD_TRAY, "DVD-SL TRAY CLOSE", "00"},
    {18, 0, 3000, MECHA_CMD_SLED_POS_HOME, "DVD-SL SLED HOME POSITION", NULL},
    {19, MECHA_CMD_TAG_ELECT_DVDSL_DETECT_ADJ, 20000, MECHA_CMD_DETECT_ADJ, "DVD-SL DETECT ADJUSTMENT", "01"}, // If this command succeeds (byte 1 is not a '1'), disable the next 4 commands.
    {20, MECHA_CMD_TAG_ELECT_DVDSL_WR_WORK0_F0, 1000, MECHA_CMD_EEPROM_WRITE, "DVD-SL DETECT WR WORK0=F0", "000a00f0"},
    {21, 0, 20000, MECHA_CMD_DETECT_ADJ, "DVD-SL DETECT ADJ (DVD-DL)", "02"},
    {22, MECHA_CMD_TAG_ELECT_DVDSL_RD_PULL_IN, 1000, MECHA_CMD_EEPROM_READ, "DVD-SL DETECT RD PULL-IN", "0001"},          // Value is acted on by ElectDiscDetectPullIn()
    {23, MECHA_CMD_TAG_ELECT_DVDSL_WR_WORK0_NEW, 1000, MECHA_CMD_EEPROM_WRITE, "DVD-SL DETECT WR WORK0=NEW", "000axxxx"}, // Use value from ElectDiscDetectPullIn()
    {24, 0, 1000, MECHA_CMD_DISC_MODE_DVDSL_12, "DISC MODE DVD-SL 12cm", NULL},
    {25, 0, 20000, MECHA_CMD_AUTO_ADJ_ST_1, "DVD-SL AUTO ADJUSTMENT (STAGE 1)", "01"},
    {26, 0, 20000, MECHA_CMD_AUTO_ADJ_ST_2, "DVD-SL AUTO ADJUSTMENT (STAGE 2)", "01"},
    {27, MECHA_CMD_TAG_ELECT_DVDSL_FE_LOOP_GAIN, 3000, MECHA_CMD_GAIN, "DVD-SL GET FE LOOP GAIN", "13"},
    {28, MECHA_CMD_TAG_ELECT_DVDSL_TE_LOOP_GAIN, 3000, MECHA_CMD_GAIN, "DVD-SL GET TE LOOP GAIN", "23"},
    {29, MECHA_CMD_TAG_ELECT_DVDSL_JITTER_256, 3000, MECHA_CMD_JITTER, "DVD-SL GET JITTER (256)", "01"},
    {30, 0, 3000, MECHA_CMD_DSP_ERROR_RATE_CTL, "DVD-SL DSP ERROR RATE (START)", "01"},
    {31, MECHA_CMD_TAG_ELECT_DVDSL_PIPOCC_RATE, 5000, MECHA_CMD_DSP_ERROR_RATE, "DVD-SL GET DSP PI+PO-CC RATE", "08"},
    {32, MECHA_CMD_TAG_ELECT_DVDSL_PONCC_RATE, 5000, MECHA_CMD_DSP_ERROR_RATE, "DVD-SL GET DSP PO-NCC RATE", "05"},
    {33, 0, 3000, MECHA_CMD_DSP_ERROR_RATE_CTL, "DVD-SL DSP ERROR RATE (END)", "00"},
    {34, 0, 3000, MECHA_CMD_FOCUS_UPDOWN, "DVD-SL STOP", "00"},
    {35, 0, 3000, MECHA_CMD_SLED_POS_HOME, "DVD-SL SLED HOME POSITION", NULL},
    {36, 0, 6000, MECHA_CMD_TRAY, "DVD-SL FIN (TRAY OPEN)", "01"},
    {0, 0, 0, MECHA_TASK_UI_CMD_MSG, "Insert test DVD-DL and press ENTER", NULL},
    {37, 0, 6000, MECHA_CMD_TRAY, "DVD-DL TRAY CLOSE", "00"},
    {38, 0, 3000, MECHA_CMD_SLED_POS_HOME, "DVD-DL SLED HOME POSITION", NULL},
    {39, 0, 20000, MECHA_CMD_DETECT_ADJ, "DVD-DL DETECT ADJUSTMENT", "02"},
    {40, MECHA_CMD_TAG_ELECT_DVDDL_DISC_DET_JUDGE, 20000, MECHA_CMD_DISC_DETECT, "DVD-DL DETECT JUDGEMENT", NULL},
    {41, 0, 1000, MECHA_CMD_DISC_MODE_DVDDL_12, "DISC MODE DVD-DL 12cm", NULL},
    {42, 0, 30000, MECHA_CMD_AUTO_ADJ_ST_1, "DVD-DL AUTO ADJUSTMENT (STAGE 1)", "01"},
    {43, 0, 40000, MECHA_CMD_AUTO_ADJ_ST_2, "DVD-DL AUTO ADJUSTMENT (STAGE 2)", "01"},
    {44, MECHA_CMD_TAG_ELECT_DVDDL_L0_FE_LOOP_GAIN, 3000, MECHA_CMD_GAIN, "DVD-DL-L0 GET FE LOOP GAIN", "13"},
    {45, MECHA_CMD_TAG_ELECT_DVDDL_L0_TE_LOOP_GAIN, 3000, MECHA_CMD_GAIN, "DVD-DL-L0 GET TE LOOP GAIN", "23"},
    {46, MECHA_CMD_TAG_ELECT_DVDDL_L0_JITTER_256, 3000, MECHA_CMD_JITTER, "DVD-DL-L0 GET JITTER (256)", "01"},
    {47, 0, 5000, MECHA_CMD_FOCUS_JUMP, "DVD-DL FOCUS JUMP", "0300"},
    {48, MECHA_CMD_TAG_ELECT_DVDDL_L1_FE_LOOP_GAIN, 3000, MECHA_CMD_GAIN, "DVD-DL-L1 GET FE LOOP GAIN", "13"},
    {49, MECHA_CMD_TAG_ELECT_DVDDL_L1_TE_LOOP_GAIN, 3000, MECHA_CMD_GAIN, "DVD-DL-L1 GET TE LOOP GAIN", "23"},
    {50, MECHA_CMD_TAG_ELECT_DVDDL_L1_JITTER_256, 3000, MECHA_CMD_JITTER, "DVD-DL-L1 GET JITTER (256)", "01"},
    {51, 0, 3000, MECHA_CMD_FOCUS_UPDOWN, "DVD-DL STOP", "00"},
    {52, MECHA_CMD_TAG_ELECT_DEX_NEWLENS, 3000, MECHA_CMD_EEPROM_WRITE, "EEPROM WR (DEX-NewLens)", "001c0000"}, // For DEX with T609K
    {0, 0, 500, MECHA_TASK_UI_CMD_WAIT, "CD WAIT 500ms", NULL},
    {53, 0, 3000, MECHA_CMD_WRITE_CHECKSUM, "ALL EEPROM CHECK SUM WR", "00"},
    {54, MECHA_CMD_TAG_ELECT_EEPROM_CHECKSUM_CHK, 3000, MECHA_CMD_READ_CHECKSUM, "ALL EEPROM CHECK SUM CHK", "00"},
    {55, 0, 3000, MECHA_CMD_SLED_POS_HOME, "DVD-DL SLED HOME POSITION", NULL},
    {56, 0, 6000, MECHA_CMD_TRAY, "DVD-DL FIN (TRAY OPEN)", "01"},
    {0, 0, 0, MECHA_TASK_UI_CMD_MSG, "Remove disc and press ENTER", NULL},
    {57, 0, 6000, MECHA_CMD_TRAY, "TRAY CLOSE", "00"},
    {58, 0, 3000, MECHA_CMD_SLED_POS_HOME, "FIN (SLED HOME)", NULL},
    {-1, -1, -1, -1, NULL, NULL}};

static const ElectMechaTaskPrep_t AutoAdj139Commands[] = { // Test CD SCD-2700/YEDS-18, DVD-SL HX-504, DVD-DL HX-505
    {1, 0, 1000, MECHA_CMD_DISC_MODE_CD_12, "DISC MODE CD 12cm", NULL},
    {2, 0, 3000, MECHA_CMD_FOCUS_UPDOWN, "FOCUS UP/DOWN END", "00"},
    {3, 0, 3000, MECHA_CMD_SLED_POS_HOME, "CD SLED HOME POSITION", NULL},
    {4, 0, 6000, MECHA_CMD_TRAY, "CD TRAY CLOSE", "00"},
    {5, 0, 6000, MECHA_CMD_TRAY, "CD START (TRAY OPEN)", "01"},
    {0, 0, 0, MECHA_TASK_UI_CMD_MSG, "Insert test CD and press ENTER", NULL},
    {6, 0, 6000, MECHA_CMD_TRAY, "CD TRAY CLOSE", "00"},
    {7, 0, 3000, MECHA_CMD_SLED_POS_HOME, "CD SLED HOME POSITION", NULL},
    {8, 0, 6000, MECHA_CMD_DETECT_ADJ, "CD DETECT ADJUSTMENT", "00"},
    {9, 0, 1000, MECHA_CMD_DISC_MODE_CD_8, "CD 8cm DISC MODE", NULL},
    {10, 0, 20000, MECHA_CMD_AUTO_ADJ_ST_1, "CD AUTO ADJUSTMENT (STAGE 1)", "01"},
    {11, 0, 20000, MECHA_CMD_AUTO_ADJ_ST_2, "CD AUTO ADJUSTMENT (STAGE 2)", "01"},
    {12, MECHA_CMD_TAG_ELECT_CD_FE_LOOP_GAIN, 3000, MECHA_CMD_GAIN, "CD GET FE LOOP GAIN", "13"},
    {13, MECHA_CMD_TAG_ELECT_CD_TE_LOOP_GAIN, 3000, MECHA_CMD_GAIN, "CD GET TE LOOP GAIN", "23"},
    {14, 0, 3000, MECHA_CMD_FOCUS_UPDOWN, "CD STOP", "00"},
    {0, 0, 1000, MECHA_TASK_UI_CMD_WAIT, "CD WAIT 1s", NULL},
    {15, 0, 3000, MECHA_CMD_SLED_POS_HOME, "CD SLED HOME POSITION", NULL},
    {16, 0, 6000, MECHA_CMD_TRAY, "CD FIN (TRAY OPEN)", "01"},
    {0, 0, 0, MECHA_TASK_UI_CMD_MSG, "Insert test DVD-SL and press ENTER", NULL},
    {17, 0, 6000, MECHA_CMD_TRAY, "DVD-SL TRAY CLOSE", "00"},
    {18, 0, 3000, MECHA_CMD_SLED_POS_HOME, "DVD-SL SLED HOME POSITION", NULL},
    {19, 0, 10000, MECHA_CMD_DETECT_ADJ, "DVD-SL DETECT ADJUSTMENT", "01"},
    {20, 0, 1000, MECHA_CMD_DISC_MODE_DVDSL_12, "DISC MODE DVD-SL 12cm", NULL},
    {21, 0, 20000, MECHA_CMD_AUTO_ADJ_ST_1, "DVD-SL AUTO ADJUSTMENT (STAGE 1)", "01"},
    {22, 0, 20000, MECHA_CMD_AUTO_ADJ_ST_2, "DVD-SL AUTO ADJUSTMENT (STAGE 2)", "01"},
    {23, MECHA_CMD_TAG_ELECT_DVDSL_FE_LOOP_GAIN, 3000, MECHA_CMD_GAIN, "DVD-SL GET FE LOOP GAIN", "13"},
    {24, MECHA_CMD_TAG_ELECT_DVDSL_TE_LOOP_GAIN, 3000, MECHA_CMD_GAIN, "DVD-SL GET TE LOOP GAIN", "23"},
    {25, MECHA_CMD_TAG_ELECT_DVDSL_JITTER_256, 3000, MECHA_CMD_JITTER, "DVD-SL GET JITTER (256)", "01"},
    {26, 0, 3000, MECHA_CMD_DSP_ERROR_RATE_CTL, "DVD-SL DSP ERROR RATE (START)", "01"},
    {27, MECHA_CMD_TAG_ELECT_DVDSL_PIPOCC_RATE, 5000, MECHA_CMD_DSP_ERROR_RATE, "DVD-SL GET DSP PI+PO-CC RATE", "08"},
    {28, MECHA_CMD_TAG_ELECT_DVDSL_PONCC_RATE, 5000, MECHA_CMD_DSP_ERROR_RATE, "DVD-SL GET DSP PO-NCC RATE", "05"},
    {29, 0, 3000, MECHA_CMD_DSP_ERROR_RATE_CTL, "DVD-SL DSP ERROR RATE (END)", "00"},
    {30, 0, 3000, MECHA_CMD_FOCUS_UPDOWN, "DVD-SL STOP", "00"},
    {31, 0, 3000, MECHA_CMD_SLED_POS_HOME, "DVD-SL SLED HOME POSITION", NULL},
    {32, 0, 6000, MECHA_CMD_TRAY, "DVD-SL FIN (TRAY OPEN)", "01"},
    {0, 0, 0, MECHA_TASK_UI_CMD_MSG, "Insert test DVD-DL and press ENTER", NULL},
    {33, 0, 6000, MECHA_CMD_TRAY, "DVD-DL TRAY CLOSE", "00"},
    {34, 0, 3000, MECHA_CMD_SLED_POS_HOME, "DVD-DL SLED HOME POSITION", NULL},
    {35, 0, 10000, MECHA_CMD_DETECT_ADJ, "DVD-DL DETECT ADJUSTMENT", "02"},
    {36, 0, 5000, MECHA_CMD_DETECT_ADJ, "DVD-DL DETECT EEPROM WRITE", "03"},
    {37, MECHA_CMD_TAG_ELECT_DVDDL_DISC_DET_JUDGE, 5000, MECHA_CMD_DISC_DETECT, "DVD-DL DETECT JUDGEMENT", NULL},
    {38, 0, 1000, MECHA_CMD_DISC_MODE_DVDDL_12, "DISC MODE DVD-DL 12cm", NULL},
    {39, 0, 20000, MECHA_CMD_AUTO_ADJ_ST_1, "DVD-DL AUTO ADJUSTMENT (STAGE 1)", "01"},
    {40, 0, 20000, MECHA_CMD_AUTO_ADJ_ST_2, "DVD-DL AUTO ADJUSTMENT (STAGE 2)", "01"},
    {41, MECHA_CMD_TAG_ELECT_DVDDL_L0_FE_LOOP_GAIN, 3000, MECHA_CMD_GAIN, "DVD-DL-L0 GET FE LOOP GAIN", "13"},
    {42, MECHA_CMD_TAG_ELECT_DVDDL_L0_TE_LOOP_GAIN, 3000, MECHA_CMD_GAIN, "DVD-DL-L0 GET TE LOOP GAIN", "23"},
    {43, MECHA_CMD_TAG_ELECT_DVDDL_L0_JITTER_256, 3000, MECHA_CMD_JITTER, "DVD-DL-L0 GET JITTER (256)", "01"},
    {44, 0, 3000, MECHA_CMD_FOCUS_JUMP, "DVD-DL FOCUS JUMP", "0300"},
    {45, MECHA_CMD_TAG_ELECT_DVDDL_L1_FE_LOOP_GAIN, 3000, MECHA_CMD_GAIN, "DVD-DL-L1 GET FE LOOP GAIN", "13"},
    {46, MECHA_CMD_TAG_ELECT_DVDDL_L1_TE_LOOP_GAIN, 3000, MECHA_CMD_GAIN, "DVD-DL-L1 GET TE LOOP GAIN", "23"},
    {47, MECHA_CMD_TAG_ELECT_DVDDL_L1_JITTER_256, 3000, MECHA_CMD_JITTER, "DVD-DL-L1 GET JITTER (256)", "01"},
    {48, 0, 3000, MECHA_CMD_FOCUS_UPDOWN, "DVD-DL STOP", "00"},
    {49, MECHA_CMD_TAG_ELECT_DEX_NEWLENS, 3000, MECHA_CMD_EEPROM_WRITE, "EEPROM WR (DEX-NewLens)", "001c0000"}, // For DEX with T609K
    {0, 0, 500, MECHA_TASK_UI_CMD_WAIT, "CD WAIT 500ms", NULL},
    {50, 0, 3000, MECHA_CMD_WRITE_CHECKSUM, "ALL EEPROM CHECK SUM WR", "00"},
    {51, MECHA_CMD_TAG_ELECT_EEPROM_CHECKSUM_CHK, 3000, MECHA_CMD_READ_CHECKSUM, "ALL EEPROM CHECK SUM CHK", "00"},
    {52, 0, 3000, MECHA_CMD_SLED_POS_HOME, "DVD-DL SLED HOME POSITION", NULL},
    {53, 0, 6000, MECHA_CMD_TRAY, "DVD-DL FIN (TRAY OPEN)", "01"},
    {0, 0, 0, MECHA_TASK_UI_CMD_MSG, "Remove disc and press ENTER", NULL},
    {54, 0, 6000, MECHA_CMD_TRAY, "TRAY CLOSE", "00"},
    {55, 0, 3000, MECHA_CMD_SLED_POS_HOME, "FIN (SLED HOME)", NULL},
    {-1, -1, -1, -1, NULL, NULL}};
static const ElectMechaTaskPrep_t AutoAdjFCommands[]   = { // Test CD SCD-2700, DVD-SL HX-504, DVD-DL HX-505
    {1, 0, 1000, MECHA_CMD_DISC_MODE_CD_12, "DISC MODE CD 12cm", NULL},
    {2, 0, 3000, MECHA_CMD_FOCUS_UPDOWN, "FOCUS UP/DOWN END", "00"},
    {3, 0, 3000, MECHA_CMD_SLED_POS_HOME, "CD SLED HOME POSITION", NULL},
    {4, 0, 6000, MECHA_CMD_TRAY, "CD TRAY CLOSE", "00"},
    {5, 0, 6000, MECHA_CMD_TRAY, "CD START (TRAY OPEN)", "01"},
    {0, 0, 0, MECHA_TASK_UI_CMD_MSG, "Insert test CD and press ENTER", NULL},
    {6, 0, 6000, MECHA_CMD_TRAY, "CD TRAY CLOSE", "00"},
    {7, 0, 3000, MECHA_CMD_SLED_POS_HOME, "CD SLED HOME POSITION", NULL},
    {8, 0, 6000, MECHA_CMD_DETECT_ADJ, "CD DETECT ADJUSTMENT", "00"},
    {9, MECHA_CMD_TAG_ELECT_OP_TYPE_ERROR, 6000, MECHA_CMD_EEPROM_READ, "CD GET CD-MIN (OP TYPE ERR)", "0002"},
    {10, 0, 1000, MECHA_CMD_DISC_MODE_CD_8, "CD 8cm DISC MODE", NULL},
    {11, 0, 20000, MECHA_CMD_AUTO_ADJ_FIX_GAIN, "CD AUTO ADJUSTMENT (FIX GAIN)", "0103"},
    {12, MECHA_CMD_TAG_ELECT_CD_FE_LOOP_GAIN, 3000, MECHA_CMD_GAIN, "CD GET FE LOOP GAIN", "13"},
    {13, MECHA_CMD_TAG_ELECT_CD_TE_LOOP_GAIN, 3000, MECHA_CMD_GAIN, "CD GET TE LOOP GAIN", "23"},
    {14, 0, 3000, MECHA_CMD_FOCUS_UPDOWN, "CD STOP", "00"},
    {0, 0, 1000, MECHA_TASK_UI_CMD_WAIT, "CD WAIT 1s", NULL},
    {15, 0, 3000, MECHA_CMD_SLED_POS_HOME, "CD SLED HOME POSITION", NULL},
    {16, 0, 6000, MECHA_CMD_TRAY, "CD FIN (TRAY OPEN)", "01"},
    {0, 0, 0, MECHA_TASK_UI_CMD_MSG, "Insert test DVD-SL and press ENTER", NULL},
    {17, 0, 6000, MECHA_CMD_TRAY, "DVD-SL TRAY CLOSE", "00"},
    {18, 0, 3000, MECHA_CMD_SLED_POS_HOME, "DVD-SL SLED HOME POSITION", NULL},
    {19, 0, 10000, MECHA_CMD_DETECT_ADJ, "DVD-SL DETECT ADJUSTMENT", "01"},
    {20, MECHA_CMD_TAG_ELECT_DISC_DET_DVDMIN_RD, 5000, MECHA_CMD_EEPROM_READ, "DISC DETECT EEPROM-DVDmin RD", "0004"},
    {21, MECHA_CMD_TAG_ELECT_DISC_DET_CDMIN_WR, 5000, MECHA_CMD_EEPROM_WRITE, "DISC DETECT EEPROM-CDmin WR", "00020000"},
    {22, MECHA_CMD_TAG_ELECT_DISC_DET_DVDMAX_WR, 5000, MECHA_CMD_EEPROM_WRITE, "DISC DETECT EEPROM-DVDmax WR", "00050000"},
    {23, 0, 3000, MECHA_CMD_WRITE_CHECKSUM, "ALL EEPROM CHECK SUM WR", "00"},
    {24, 0, 5000, MECHA_CMD_UPLOAD_TO_RAM, "COPY EEPROM DATA TO MECHACON", "02"},
    {25, MECHA_CMD_TAG_ELECT_DVDSL_DISC_DET_JUDGE, 5000, MECHA_CMD_EEPROM_READ, "DISC DETECT EEPROM-CDmax RD", "0003"},
    {26, 0, 1000, MECHA_CMD_DISC_MODE_DVDSL_12, "DISC MODE DVD-SL 12cm", NULL},
    {27, 0, 20000, MECHA_CMD_AUTO_ADJ_ST_1, "DVD-SL AUTO ADJUSTMENT (STAGE 1)", "01"},
    {28, 0, 20000, MECHA_CMD_AUTO_ADJ_ST_2, "DVD-SL AUTO ADJUSTMENT (STAGE 2)", "01"},
    {29, MECHA_CMD_TAG_ELECT_DVDSL_FE_LOOP_GAIN, 3000, MECHA_CMD_GAIN, "DVD-SL GET FE LOOP GAIN", "13"},
    {30, MECHA_CMD_TAG_ELECT_DVDSL_TE_LOOP_GAIN, 3000, MECHA_CMD_GAIN, "DVD-SL GET TE LOOP GAIN", "23"},
    {31, MECHA_CMD_TAG_ELECT_DVDSL_JITTER_256, 3000, MECHA_CMD_JITTER, "DVD-SL GET JITTER (256)", "01"},
    {32, 0, 3000, MECHA_CMD_DSP_ERROR_RATE_CTL, "DVD-SL DSP ERROR RATE (START)", "01"},
    {33, MECHA_CMD_TAG_ELECT_DVDSL_PIPOCC_RATE, 5000, MECHA_CMD_DSP_ERROR_RATE, "DVD-SL GET DSP PI+PO-CC RATE", "08"},
    {34, MECHA_CMD_TAG_ELECT_DVDSL_PONCC_RATE, 5000, MECHA_CMD_DSP_ERROR_RATE, "DVD-SL GET DSP PO-NCC RATE", "05"},
    {35, 0, 3000, MECHA_CMD_DSP_ERROR_RATE_CTL, "DVD-SL DSP ERROR RATE (END)", "00"},
    {36, 0, 3000, MECHA_CMD_FOCUS_UPDOWN, "DVD-SL STOP", "00"},
    {37, 0, 3000, MECHA_CMD_SLED_POS_HOME, "DVD-SL SLED HOME POSITION", NULL},
    {38, 0, 6000, MECHA_CMD_TRAY, "DVD-SL FIN (TRAY OPEN)", "01"},
    {0, 0, 0, MECHA_TASK_UI_CMD_MSG, "Insert test DVD-DL and press ENTER", NULL},
    {39, 0, 6000, MECHA_CMD_TRAY, "DVD-DL TRAY CLOSE", "00"},
    {40, 0, 3000, MECHA_CMD_SLED_POS_HOME, "DVD-DL SLED HOME POSITION", NULL},
    {41, MECHA_CMD_TAG_ELECT_DVDDL_DISC_DET_JUDGE, 5000, MECHA_CMD_DISC_DETECT, "DVD-DL DETECT JUDGEMENT", NULL},
    {42, 0, 1000, MECHA_CMD_DISC_MODE_DVDDL_12, "DISC MODE DVD-DL 12cm", NULL},
    {43, 0, 20000, MECHA_CMD_AUTO_ADJ_ST_1, "DVD-DL AUTO ADJUSTMENT (STAGE 1)", "01"},
    {44, 0, 20000, MECHA_CMD_AUTO_ADJ_ST_2, "DVD-DL AUTO ADJUSTMENT (STAGE 2)", "01"},
    {45, MECHA_CMD_TAG_ELECT_DVDDL_L0_FE_LOOP_GAIN, 3000, MECHA_CMD_GAIN, "DVD-DL-L0 GET FE LOOP GAIN", "13"},
    {46, MECHA_CMD_TAG_ELECT_DVDDL_L0_TE_LOOP_GAIN, 3000, MECHA_CMD_GAIN, "DVD-DL-L0 GET TE LOOP GAIN", "23"},
    {47, MECHA_CMD_TAG_ELECT_DVDDL_L0_JITTER_256, 3000, MECHA_CMD_JITTER, "DVD-DL-L0 GET JITTER (256)", "01"},
    {48, 0, 3000, MECHA_CMD_FOCUS_JUMP, "DVD-DL FOCUS JUMP", "0300"},
    {49, MECHA_CMD_TAG_ELECT_DVDDL_L1_FE_LOOP_GAIN, 3000, MECHA_CMD_GAIN, "DVD-DL-L1 GET FE LOOP GAIN", "13"},
    {50, MECHA_CMD_TAG_ELECT_DVDDL_L1_TE_LOOP_GAIN, 3000, MECHA_CMD_GAIN, "DVD-DL-L1 GET TE LOOP GAIN", "23"},
    {51, MECHA_CMD_TAG_ELECT_DVDDL_L1_JITTER_256, 3000, MECHA_CMD_JITTER, "DVD-DL-L1 GET JITTER (256)", "01"},
    {52, 0, 3000, MECHA_CMD_FOCUS_UPDOWN, "DVD-DL STOP", "00"},
    {53, 0, 3000, MECHA_CMD_WRITE_CHECKSUM, "ALL EEPROM CHECK SUM WR", "00"},
    {54, MECHA_CMD_TAG_ELECT_EEPROM_CHECKSUM_CHK, 3000, MECHA_CMD_READ_CHECKSUM, "ALL EEPROM CHECK SUM CHK", "00"},
    {55, 0, 3000, MECHA_CMD_SLED_POS_HOME, "DVD-DL SLED HOME POSITION", NULL},
    {56, 0, 6000, MECHA_CMD_TRAY, "DVD-DL FIN (TRAY OPEN)", "01"},
    {0, 0, 0, MECHA_TASK_UI_CMD_MSG, "Remove disc and press ENTER", NULL},
    {57, 0, 6000, MECHA_CMD_TRAY, "TRAY CLOSE", "00"},
    {58, 0, 3000, MECHA_CMD_SLED_POS_HOME, "FIN (SLED HOME)", NULL},
    {-1, -1, -1, -1, NULL, NULL}};

static const ElectMechaTaskPrep_t AutoAdjGCommands[]   = { // Test CD SCD-2700/YEDS-18, DVD-SL HX-504, DVD-DL HX-505
    {1, 0, 1000, MECHA_CMD_DISC_MODE_CD_12, "DISC MODE CD 12cm", NULL},
    {2, 0, 3000, MECHA_CMD_FOCUS_UPDOWN, "FOCUS UP/DOWN END", "00"},
    {3, 0, 3000, MECHA_CMD_SLED_POS_HOME, "CD SLED HOME POSITION", NULL},
    {4, 0, 6000, MECHA_CMD_TRAY, "CD TRAY CLOSE", "00"},
    {5, 0, 6000, MECHA_CMD_TRAY, "CD START (TRAY OPEN)", "01"},
    {0, 0, 0, MECHA_TASK_UI_CMD_MSG, "Insert test CD and press ENTER", NULL},
    {6, 0, 6000, MECHA_CMD_TRAY, "CD TRAY CLOSE", "00"},
    {7, 0, 3000, MECHA_CMD_SLED_POS_HOME, "CD SLED HOME POSITION", NULL},
    {8, 0, 6000, MECHA_CMD_DETECT_ADJ, "CD DETECT ADJUSTMENT", "00"},
    {9, MECHA_CMD_TAG_ELECT_OP_TYPE_ERROR, 6000, MECHA_CMD_EEPROM_READ, "CD GET CD-MAX (OP TYPE ERR)", "0003"},
    {10, 0, 1000, MECHA_CMD_DISC_MODE_CD_8, "CD 8cm DISC MODE", NULL},
    {11, 0, 20000, MECHA_CMD_AUTO_ADJ_ST_1, "CD AUTO ADJUSTMENT (STAGE 1)", "01"},
    {12, 0, 20000, MECHA_CMD_AUTO_ADJ_ST_2, "CD AUTO ADJUSTMENT (STAGE 2)", "01"},
    {13, MECHA_CMD_TAG_ELECT_CD_FE_LOOP_GAIN, 3000, MECHA_CMD_GAIN, "CD GET FE LOOP GAIN", "13"},
    {14, MECHA_CMD_TAG_ELECT_CD_TE_LOOP_GAIN, 3000, MECHA_CMD_GAIN, "CD GET TE LOOP GAIN", "23"},
    {15, 0, 3000, MECHA_CMD_FOCUS_UPDOWN, "CD STOP", "00"},
    {0, 0, 1000, MECHA_TASK_UI_CMD_WAIT, "CD WAIT 1s", NULL},
    {16, 0, 3000, MECHA_CMD_SLED_POS_HOME, "CD SLED HOME POSITION", NULL},
    {17, 0, 6000, MECHA_CMD_TRAY, "CD FIN (TRAY OPEN)", "01"},
    {0, 0, 0, MECHA_TASK_UI_CMD_MSG, "Insert test DVD-SL and press ENTER", NULL},
    {18, 0, 6000, MECHA_CMD_TRAY, "DVD-SL TRAY CLOSE", "00"},
    {19, 0, 3000, MECHA_CMD_SLED_POS_HOME, "DVD-SL SLED HOME POSITION", NULL},
    {20, 0, 10000, MECHA_CMD_DETECT_ADJ, "DVD-SL DETECT ADJUSTMENT", "01"},
    {21, 0, 5000, MECHA_CMD_DETECT_ADJ, "DISC DETECT EEPROM WR", "03"},
    {22, 0, 5000, MECHA_CMD_UPLOAD_TO_RAM, "COPY EEPROM DATA TO MECHACON", "02"},
    {23, MECHA_CMD_TAG_ELECT_DISC_DET_DVDMIN_RD, 5000, MECHA_CMD_EEPROM_READ, "DISC DETECT EEPROM-DVDmin RD", "0004"},
    {24, MECHA_CMD_TAG_ELECT_DVDSL_DISC_DET_JUDGE, 5000, MECHA_CMD_EEPROM_READ, "DISC DETECT EEPROM-CDmax RD", "0003"},
    {25, 0, 1000, MECHA_CMD_DISC_MODE_DVDSL_12, "DISC MODE DVD-SL 12cm", NULL},
    {26, 0, 20000, MECHA_CMD_AUTO_ADJ_FIX_GAIN, "DVD-SL AUTO ADJUSTMENT (Fix Gain Mode)", "0105"},
    {27, MECHA_CMD_TAG_ELECT_DVDSL_FE_LOOP_GAIN, 3000, MECHA_CMD_GAIN, "DVD-SL GET FE LOOP GAIN", "13"},
    {28, MECHA_CMD_TAG_ELECT_DVDSL_TE_LOOP_GAIN, 3000, MECHA_CMD_GAIN, "DVD-SL GET TE LOOP GAIN", "23"},
    {29, MECHA_CMD_TAG_ELECT_DVDSL_JITTER_256_RTY, 3000, MECHA_CMD_JITTER, "DVD-SL GET JITTER (256)_WITH_RETRY", "01"},
    {30, MECHA_CMD_TAG_ELECT_DVD_SET_DSP_JITTER, 3000, MECHA_CMD_SET_DSP, "DVD-SL SET-DSP FOR JITTER (256)", "d6d80000"},
    {31, MECHA_CMD_TAG_ELECT_DVDSL_JITTER_256, 3000, MECHA_CMD_JITTER, "DVD-SL GET JITTER (256)", "01"},
    {32, 0, 3000, MECHA_CMD_SET_DSP, "DVD-SL RESET-DSP FOR JITTER (256)", "d6de0000"},
    {33, 0, 3000, MECHA_CMD_DSP_ERROR_RATE_CTL, "DVD-SL DSP ERROR RATE (START)", "01"},
    {34, MECHA_CMD_TAG_ELECT_DVDSL_PIPOCC_RATE, 3000, MECHA_CMD_DSP_ERROR_RATE, "DVD-SL GET DSP PI+PO-CC RATE", "08"},
    {35, MECHA_CMD_TAG_ELECT_DVDSL_PONCC_RATE, 5000, MECHA_CMD_DSP_ERROR_RATE, "DVD-SL GET DSP PO-NCC RATE", "05"},
    {36, 0, 5000, MECHA_CMD_DSP_ERROR_RATE_CTL, "DVD-SL DSP ERROR RATE (END)", "00"},
    {37, 0, 3000, MECHA_CMD_FOCUS_UPDOWN, "DVD-SL STOP", "00"},
    {38, 0, 3000, MECHA_CMD_SLED_POS_HOME, "DVD-SL SLED HOME POSITION", NULL},
    {39, 0, 6000, MECHA_CMD_TRAY, "DVD-SL FIN (TRAY OPEN)", "01"},
    {0, 0, 0, MECHA_TASK_UI_CMD_MSG, "Insert test DVD-DL and press ENTER", NULL},
    {40, 0, 6000, MECHA_CMD_TRAY, "DVD-DL TRAY CLOSE", "00"},
    {41, 0, 3000, MECHA_CMD_SLED_POS_HOME, "DVD-DL SLED HOME POSITION", NULL},
    {42, MECHA_CMD_TAG_ELECT_DVDDL_DISC_DET_JUDGE, 5000, MECHA_CMD_DISC_DETECT, "DVD-DL DETECT JUDGEMENT", NULL},
    {43, 0, 1000, MECHA_CMD_DISC_MODE_DVDDL_12, "DISC MODE DVD-DL 12cm", NULL},
    {44, 0, 20000, MECHA_CMD_AUTO_ADJ_ST_1, "DVD-DL AUTO ADJUSTMENT (STAGE 1)", "01"},
    {45, 0, 20000, MECHA_CMD_AUTO_ADJ_ST_2, "DVD-DL AUTO ADJUSTMENT (STAGE 2)", "01"},
    {46, MECHA_CMD_TAG_ELECT_DVDDL_L0_FE_LOOP_GAIN, 3000, MECHA_CMD_GAIN, "DVD-DL-L0 GET FE LOOP GAIN", "13"},
    {47, MECHA_CMD_TAG_ELECT_DVDDL_L0_TE_LOOP_GAIN, 3000, MECHA_CMD_GAIN, "DVD-DL-L0 GET TE LOOP GAIN", "23"},
    {48, MECHA_CMD_TAG_ELECT_DVDDL_L0_JITTER_256_RTY, 3000, MECHA_CMD_JITTER, "DVD-DL-L0 GET JITTER (256)_WITH_RETRY", "01"},
    {49, MECHA_CMD_TAG_ELECT_DVD_SET_DSP_JITTER, 3000, MECHA_CMD_SET_DSP, "DVD-DL-L0 SET-DSP FOR JITTER (256)", "d6d80000"},
    {50, MECHA_CMD_TAG_ELECT_DVDDL_L0_JITTER_256, 3000, MECHA_CMD_JITTER, "DVD-DL-L0 GET JITTER (256)", "01"},
    {51, 0, 3000, MECHA_CMD_SET_DSP, "DVD-DL-L0 RESET-DSP FOR JITTER (256)", "d6de0000"},
    {52, 0, 3000, MECHA_CMD_FOCUS_JUMP, "DVD-DL FOCUS JUMP", "0300"},
    {53, MECHA_CMD_TAG_ELECT_DVDDL_L1_FE_LOOP_GAIN, 3000, MECHA_CMD_GAIN, "DVD-DL-L1 GET FE LOOP GAIN", "13"},
    {54, MECHA_CMD_TAG_ELECT_DVDDL_L1_TE_LOOP_GAIN, 3000, MECHA_CMD_GAIN, "DVD-DL-L1 GET TE LOOP GAIN", "23"},
    {55, MECHA_CMD_TAG_ELECT_DVDDL_L1_JITTER_256_RTY, 3000, MECHA_CMD_JITTER, "DVD-DL-L1 GET JITTER (256)_WITH_RETRY", "01"},
    {56, MECHA_CMD_TAG_ELECT_DVD_SET_DSP_JITTER, 3000, MECHA_CMD_SET_DSP, "DVD-DL-L1 SET-DSP FOR JITTER (256)", "d6d80000"},
    {57, MECHA_CMD_TAG_ELECT_DVDDL_L1_JITTER_256, 3000, MECHA_CMD_JITTER, "DVD-DL-L1 GET JITTER (256)", "01"},
    {58, 0, 3000, MECHA_CMD_SET_DSP, "DVD-DL-L1 RESET-DSP FOR JITTER (256)", "d6de0000"},
    {59, 0, 3000, MECHA_CMD_FOCUS_UPDOWN, "DVD-DL STOP", "00"},
    {60, 0, 3000, MECHA_CMD_WRITE_CHECKSUM, "ALL EEPROM CHECK SUM WR", "00"},
    {61, MECHA_CMD_TAG_ELECT_EEPROM_CHECKSUM_CHK, 3000, MECHA_CMD_READ_CHECKSUM, "ALL EEPROM CHECK SUM CHK", "00"},
    {62, 0, 3000, MECHA_CMD_SLED_POS_HOME, "DVD-DL SLED HOME POSITION", NULL},
    {63, 0, 6000, MECHA_CMD_TRAY, "DVD-DL FIN (TRAY OPEN)", "01"},
    {0, 0, 0, MECHA_TASK_UI_CMD_MSG, "Remove disc and press ENTER", NULL},
    {64, 0, 6000, MECHA_CMD_TRAY, "TRAY CLOSE", "00"},
    {65, 0, 3000, MECHA_CMD_SLED_POS_HOME, "FIN (SLED HOME)", NULL},
    {-1, -1, -1, -1, NULL, NULL}};

static const ElectMechaTaskPrep_t AutoAdjG2Commands[]  = { // Test CD SCD-2700, DVD-SL HX-504, DVD-DL HX-505
    {1, 0, 1000, MECHA_CMD_DISC_MODE_CD_12, "DISC MODE CD 12cm", NULL},
    {2, 0, 3000, MECHA_CMD_FOCUS_UPDOWN, "FOCUS UP/DOWN END", "00"},
    {3, 0, 3000, MECHA_CMD_SLED_POS_HOME, "CD SLED HOME POSITION", NULL},
    {4, 0, 6000, MECHA_CMD_TRAY, "CD TRAY CLOSE", "00"},
    {5, 0, 6000, MECHA_CMD_TRAY, "CD START (TRAY OPEN)", "01"},
    {0, 0, 0, MECHA_TASK_UI_CMD_MSG, "Insert test CD and press ENTER", NULL},
    {6, 0, 6000, MECHA_CMD_TRAY, "CD TRAY CLOSE", "00"},
    {7, 0, 3000, MECHA_CMD_SLED_POS_HOME, "CD SLED HOME POSITION", NULL},
    {8, 0, 6000, MECHA_CMD_DETECT_ADJ, "CD DETECT ADJUSTMENT", "00"},
    {9, MECHA_CMD_TAG_ELECT_OP_TYPE_ERROR, 6000, MECHA_CMD_EEPROM_READ, "CD GET CD-MAX (OP TYPE ERR)", "0003"},
    {10, 0, 1000, MECHA_CMD_DISC_MODE_CD_8, "CD 8cm DISC MODE", NULL},
    {11, 0, 20000, MECHA_CMD_AUTO_ADJ_ST_1, "CD AUTO ADJUSTMENT (STAGE 1)", "01"},
    {12, 0, 20000, MECHA_CMD_AUTO_ADJ_ST_2, "CD AUTO ADJUSTMENT (STAGE 2)", "01"},
    {13, MECHA_CMD_TAG_ELECT_CD_FE_LOOP_GAIN, 3000, MECHA_CMD_GAIN, "CD GET FE LOOP GAIN", "13"},
    {14, MECHA_CMD_TAG_ELECT_CD_TE_LOOP_GAIN, 3000, MECHA_CMD_GAIN, "CD GET TE LOOP GAIN", "23"},
    {15, 0, 3000, MECHA_CMD_FOCUS_UPDOWN, "CD STOP", "00"},
    {0, 0, 1000, MECHA_TASK_UI_CMD_WAIT, "CD WAIT 1s", NULL},
    {16, MECHA_CMD_TAG_ELECT_CD_FCS_CHECK, 20000, MECHA_CMD_FCS_SEARCH_CHECK, "CD FCS SEARCH CHECK", "01"},
    {17, 0, 3000, MECHA_CMD_FOCUS_UPDOWN, "CD STOP", "00"},
    {18, 0, 3000, MECHA_CMD_SLED_POS_HOME, "CD SLED HOME POSITION", NULL},
    {19, 0, 6000, MECHA_CMD_TRAY, "CD FIN (TRAY OPEN)", "01"},
    {0, 0, 0, MECHA_TASK_UI_CMD_MSG, "Insert test DVD-SL and press ENTER", NULL},
    {20, 0, 6000, MECHA_CMD_TRAY, "DVD-SL TRAY CLOSE", "00"},
    {21, 0, 3000, MECHA_CMD_SLED_POS_HOME, "DVD-SL SLED HOME POSITION", NULL},
    {22, 0, 10000, MECHA_CMD_DETECT_ADJ, "DVD-SL DETECT ADJUSTMENT", "01"},
    {23, 0, 5000, MECHA_CMD_DETECT_ADJ, "DISC DETECT EEPROM WR", "03"},
    {24, MECHA_CMD_TAG_ELECT_DISC_DET_DVDMIN_RD, 5000, MECHA_CMD_EEPROM_READ, "DISC DETECT EEPROM-DVDmin RD", "0004"},
    {25, MECHA_CMD_TAG_ELECT_DVDSL_DISC_DET_JUDGE, 5000, MECHA_CMD_EEPROM_READ, "DISC DETECT EEPROM-CDmax RD", "0003"},
    {26, 0, 1000, MECHA_CMD_DISC_MODE_DVDSL_12, "DISC MODE DVD-SL 12cm", NULL},
    {27, 0, 20000, MECHA_CMD_AUTO_ADJ_FIX_GAIN, "DVD-SL AUTO ADJUSTMENT (Fix Gain Mode)", "0105"},
    {28, MECHA_CMD_TAG_ELECT_DVDSL_FE_LOOP_GAIN, 3000, MECHA_CMD_GAIN, "DVD-SL GET FE LOOP GAIN", "13"},
    {29, MECHA_CMD_TAG_ELECT_DVDSL_TE_LOOP_GAIN, 3000, MECHA_CMD_GAIN, "DVD-SL GET TE LOOP GAIN", "23"},
    {30, MECHA_CMD_TAG_ELECT_DVDSL_JITTER_256_RTY, 3000, MECHA_CMD_JITTER, "DVD-SL GET JITTER (256)_WITH_RETRY", "01"},
    {31, MECHA_CMD_TAG_ELECT_DVD_SET_DSP_JITTER, 3000, MECHA_CMD_SET_DSP, "DVD-SL SET-DSP FOR JITTER (256)", "d6d80000"},
    {32, MECHA_CMD_TAG_ELECT_DVDSL_JITTER_256, 3000, MECHA_CMD_JITTER, "DVD-SL GET JITTER (256)", "01"},
    {33, 0, 3000, MECHA_CMD_SET_DSP, "DVD-SL RESET-DSP FOR JITTER (256)", "d6de0000"},
    {34, 0, 3000, MECHA_CMD_DSP_ERROR_RATE_CTL, "DVD-SL DSP ERROR RATE (START)", "01"},
    {35, MECHA_CMD_TAG_ELECT_DVDSL_PIPOCC_RATE, 3000, MECHA_CMD_DSP_ERROR_RATE, "DVD-SL GET DSP PI+PO-CC RATE", "08"},
    {36, MECHA_CMD_TAG_ELECT_DVDSL_PONCC_RATE, 5000, MECHA_CMD_DSP_ERROR_RATE, "DVD-SL GET DSP PO-NCC RATE", "05"},
    {37, 0, 5000, MECHA_CMD_DSP_ERROR_RATE_CTL, "DVD-SL DSP ERROR RATE (END)", "00"},
    {38, 0, 3000, MECHA_CMD_FOCUS_UPDOWN, "DVD-SL STOP", "00"},
    {0, 0, 1000, MECHA_TASK_UI_CMD_WAIT, "CD WAIT 1s", NULL},
    {39, MECHA_CMD_TAG_ELECT_DVDSL_MIRR, 3000, MECHA_CMD_MIRR_CHECK, "DVD-SL MIRR CHECK", NULL},
    {40, MECHA_CMD_TAG_ELECT_DVDSL_MIRR_EEPROM_WR, 6000, MECHA_CMD_EEPROM_WRITE, "DVD-SL EEPROM WR 0x03F-3019", "003f3019"},
    {41, MECHA_CMD_TAG_ELECT_DVDSL_MIRR_EEPROM_WR, 6000, MECHA_CMD_EEPROM_WRITE, "DVD-SL EEPROM WR 0x040-3039", "00403039"},
    {42, 0, 3000, MECHA_CMD_SLED_POS_HOME, "DVD-SL SLED HOME POSITION", NULL},
    {43, 0, 6000, MECHA_CMD_TRAY, "DVD-SL FIN (TRAY OPEN)", "01"},
    {0, 0, 0, MECHA_TASK_UI_CMD_MSG, "Insert test DVD-DL and press ENTER", NULL},
    {44, 0, 6000, MECHA_CMD_TRAY, "DVD-DL TRAY CLOSE", "00"},
    {45, 0, 3000, MECHA_CMD_SLED_POS_HOME, "DVD-DL SLED HOME POSITION", NULL},
    {46, MECHA_CMD_TAG_ELECT_DVDDL_DISC_DET_JUDGE, 5000, MECHA_CMD_DISC_DETECT, "DVD-DL DETECT JUDGEMENT", NULL},
    {47, 0, 1000, MECHA_CMD_DISC_MODE_DVDDL_12, "DISC MODE DVD-DL 12cm", NULL},
    {48, 0, 20000, MECHA_CMD_AUTO_ADJ_ST_1, "DVD-DL AUTO ADJUSTMENT (STAGE 1)", "01"},
    {49, 0, 20000, MECHA_CMD_AUTO_ADJ_ST_2, "DVD-DL AUTO ADJUSTMENT (STAGE 2)", "01"},
    {50, MECHA_CMD_TAG_ELECT_DVDDL_L0_FE_LOOP_GAIN, 3000, MECHA_CMD_GAIN, "DVD-DL-L0 GET FE LOOP GAIN", "13"},
    {51, MECHA_CMD_TAG_ELECT_DVDDL_L0_TE_LOOP_GAIN, 3000, MECHA_CMD_GAIN, "DVD-DL-L0 GET TE LOOP GAIN", "23"},
    {52, MECHA_CMD_TAG_ELECT_DVDDL_L0_JITTER_256_RTY, 3000, MECHA_CMD_JITTER, "DVD-DL-L0 GET JITTER (256)_WITH_RETRY", "01"},
    {53, MECHA_CMD_TAG_ELECT_DVD_SET_DSP_JITTER, 3000, MECHA_CMD_SET_DSP, "DVD-DL-L0 SET-DSP FOR JITTER (256)", "d6d80000"},
    {54, MECHA_CMD_TAG_ELECT_DVDDL_L0_JITTER_256, 3000, MECHA_CMD_JITTER, "DVD-DL-L0 GET JITTER (256)", "01"},
    {55, 0, 3000, MECHA_CMD_SET_DSP, "DVD-DL-L0 RESET-DSP FOR JITTER (256)", "d6de0000"},
    {56, 0, 3000, MECHA_CMD_FOCUS_JUMP, "DVD-DL FOCUS JUMP", "0300"},
    {57, MECHA_CMD_TAG_ELECT_DVDDL_L1_FE_LOOP_GAIN, 3000, MECHA_CMD_GAIN, "DVD-DL-L1 GET FE LOOP GAIN", "13"},
    {58, MECHA_CMD_TAG_ELECT_DVDDL_L1_TE_LOOP_GAIN, 3000, MECHA_CMD_GAIN, "DVD-DL-L1 GET TE LOOP GAIN", "23"},
    {59, MECHA_CMD_TAG_ELECT_DVDDL_L1_JITTER_256_RTY, 3000, MECHA_CMD_JITTER, "DVD-DL-L1 GET JITTER (256)_WITH_RETRY", "01"},
    {60, MECHA_CMD_TAG_ELECT_DVD_SET_DSP_JITTER, 3000, MECHA_CMD_SET_DSP, "DVD-DL-L1 SET-DSP FOR JITTER (256)", "d6d80000"},
    {61, MECHA_CMD_TAG_ELECT_DVDDL_L1_JITTER_256, 3000, MECHA_CMD_JITTER, "DVD-DL-L1 GET JITTER (256)", "01"},
    {62, 0, 3000, MECHA_CMD_SET_DSP, "DVD-DL-L1 RESET-DSP FOR JITTER (256)", "d6de0000"},
    {63, 0, 3000, MECHA_CMD_FOCUS_UPDOWN, "DVD-DL STOP", "00"},
    {64, 0, 3000, MECHA_CMD_WRITE_CHECKSUM, "ALL EEPROM CHECK SUM WR", "00"},
    {65, MECHA_CMD_TAG_ELECT_EEPROM_CHECKSUM_CHK, 3000, MECHA_CMD_READ_CHECKSUM, "ALL EEPROM CHECK SUM CHK", "00"},
    {66, 0, 3000, MECHA_CMD_SLED_POS_HOME, "DVD-DL SLED HOME POSITION", NULL},
    {67, 0, 6000, MECHA_CMD_TRAY, "DVD-DL FIN (TRAY OPEN)", "01"},
    {0, 0, 0, MECHA_TASK_UI_CMD_MSG, "Remove disc and press ENTER", NULL},
    {68, 0, 6000, MECHA_CMD_TRAY, "TRAY CLOSE", "00"},
    {69, 0, 3000, MECHA_CMD_SLED_POS_HOME, "FIN (SLED HOME)", NULL},
    {-1, -1, -1, -1, NULL, NULL}};

static const ElectMechaTaskPrep_t AutoAdj140Commands[] = { // Test CD SCD-2700, DVD-SL TDV-520CSC, DVD-DL TDV-540CSC
    {1, 0, 1000, MECHA_CMD_DISC_MODE_CD_12, "DISC MODE CD 12cm", NULL},
    {2, 0, 3000, MECHA_CMD_FOCUS_UPDOWN, "FOCUS UP/DOWN END", "00"},
    {3, 0, 3000, MECHA_CMD_SLED_POS_HOME, "CD SLED HOME POSITION", NULL},
    {4, 0, 6000, MECHA_CMD_TRAY, "CD TRAY CLOSE", "00"},
    {5, 0, 6000, MECHA_CMD_TRAY, "CD START (TRAY OPEN)", "01"},
    {0, 0, 0, MECHA_TASK_UI_CMD_MSG, "Insert test CD and press ENTER", NULL},
    {6, 0, 6000, MECHA_CMD_TRAY, "CD TRAY CLOSE", "00"},
    {7, 0, 3000, MECHA_CMD_SLED_POS_HOME, "CD SLED HOME POSITION", NULL},
    {8, 0, 15000, MECHA_CMD_DETECT_ADJ, "CD DETECT ADJUSTMENT", "00"},
    {9, 0, 100, MECHA_TASK_UI_CMD_WAIT, "CD WAIT 100ms", NULL},
    {10, MECHA_CMD_TAG_ELECT_OP_TYPE_ERROR, 6000, MECHA_CMD_EEPROM_READ, "CD GET CD-MAX (OP TYPE ERR)", "0034"},
    {11, 0, 1000, MECHA_CMD_DISC_MODE_CD_8, "CD 8cm DISC MODE", NULL},
    {12, 0, 30000, MECHA_CMD_AUTO_ADJ_ST_12, "CD AUTO ADJUSTMENT (1+2)", "01"},
    {13, MECHA_CMD_TAG_ELECT_CD_FE_LOOP_GAIN, 3000, MECHA_CMD_GAIN, "CD GET FE LOOP GAIN", "13"},
    {14, MECHA_CMD_TAG_ELECT_CD_TE_LOOP_GAIN, 3000, MECHA_CMD_GAIN, "CD GET TE LOOP GAIN", "23"},
    {15, 0, 3000, MECHA_CMD_TRACKING, "CD TRACKING OFF", "00"},
    {16, MECHA_CMD_TAG_ELECT_CD_TPP, 3000, MECHA_CMD_TPP, "CD TPP CHECK", NULL},
    {17, 0, 3000, MECHA_CMD_TRACKING, "CD TRACKING ON", "01"},
    {18, 0, 3000, MECHA_CMD_FOCUS_UPDOWN, "CD STOP", "00"},
    {0, 0, 1000, MECHA_TASK_UI_CMD_WAIT, "CD WAIT 1s", NULL},
    {19, MECHA_CMD_TAG_ELECT_CD_FCS_CHECK, 20000, MECHA_CMD_FCS_SEARCH_CHECK, "CD FCS SEARCH CHECK", "01"},
    {20, 0, 3000, MECHA_CMD_FOCUS_UPDOWN, "CD STOP", "00"},
    {21, 0, 3000, MECHA_CMD_SLED_POS_HOME, "CD SLED HOME POSITION", NULL},
    {22, 0, 6000, MECHA_CMD_TRAY, "CD FIN (TRAY OPEN)", "01"},
    {0, 0, 0, MECHA_TASK_UI_CMD_MSG, "Insert test DVD-SL and press ENTER", NULL},
    {23, 0, 6000, MECHA_CMD_TRAY, "DVD-SL TRAY CLOSE", "00"},
    {24, 0, 3000, MECHA_CMD_SLED_POS_HOME, "DVD-SL SLED HOME POSITION", NULL},
    {25, 0, 10000, MECHA_CMD_DETECT_ADJ, "DVD-SL DETECT ADJUSTMENT", "01"},
    {0, 0, 100, MECHA_TASK_UI_CMD_WAIT, "CD WAIT 100ms", NULL},
    {26, 0, 5000, MECHA_CMD_DETECT_ADJ, "DISC DETECT DATA TO EEPROM WR", "03"},
    {0, 0, 100, MECHA_TASK_UI_CMD_WAIT, "CD WAIT 100ms", NULL},
    {27, MECHA_CMD_TAG_ELECT_DISC_DET_DVDMIN_RD, 5000, MECHA_CMD_EEPROM_READ, "DISC DETECT EEPROM RD", "0035"},
    {28, MECHA_CMD_TAG_ELECT_DVDSL_DISC_DET_JUDGE, 5000, MECHA_CMD_EEPROM_READ, "DISC DETECT EEPROM RD", "0034"},
    {29, 0, 1000, MECHA_CMD_DISC_MODE_DVDSL_12, "DISC MODE DVD-SL 12cm", NULL},
    {30, 0, 30000, MECHA_CMD_AUTO_ADJ_FIX_GAIN, "DVD-SL AUTO ADJUSTMENT (Fix Gain Mode)", "0105"},
    {0, 0, 100, MECHA_TASK_UI_CMD_WAIT, "CD WAIT 100ms", NULL},
    {31, MECHA_CMD_TAG_ELECT_DVDSL_RFDC_LEVEL, 3000, MECHA_CMD_RFDC_LEVEL, "DVD-SL GET RF DC LEVEL", NULL},
    {32, MECHA_CMD_TAG_ELECT_DVDSL_FE_LOOP_GAIN, 3000, MECHA_CMD_GAIN, "DVD-SL GET FE LOOP GAIN", "13"},
    {33, MECHA_CMD_TAG_ELECT_DVDSL_TE_LOOP_GAIN, 3000, MECHA_CMD_GAIN, "DVD-SL GET TE LOOP GAIN", "23"},
    {34, MECHA_CMD_TAG_ELECT_DVDSL_JITTER_256_RTY, 3000, MECHA_CMD_JITTER, "DVD-SL GET JITTER (256)_WITH_RETRY", "01"},
    {35, MECHA_CMD_TAG_ELECT_DVD_SET_DSP_JITTER, 3000, MECHA_CMD_SET_DSP, "DVD-SL SET-DSP FOR JITTER (256)", "d6d80000"},
    {36, MECHA_CMD_TAG_ELECT_DVDSL_JITTER_256, 3000, MECHA_CMD_JITTER, "DVD-SL GET JITTER (256)", "01"},
    {37, 0, 3000, MECHA_CMD_SET_DSP, "DVD-SL RESET-DSP FOR JITTER (256)", "d6de0000"},
    {38, 0, 3000, MECHA_CMD_DSP_ERROR_RATE_CTL, "DVD-SL DSP ERROR RATE (START)", "01"},
    {39, MECHA_CMD_TAG_ELECT_DVDSL_PIPOCC_RATE, 3000, MECHA_CMD_DSP_ERROR_RATE, "DVD-SL GET DSP PI+PO-CC RATE", "08"},
    {40, MECHA_CMD_TAG_ELECT_DVDSL_PONCC_RATE, 5000, MECHA_CMD_DSP_ERROR_RATE, "DVD-SL GET DSP PO-NCC RATE", "05"},
    {41, 0, 5000, MECHA_CMD_DSP_ERROR_RATE_CTL, "DVD-SL DSP ERROR RATE (END)", "00"},
    {42, 0, 3000, MECHA_CMD_FOCUS_UPDOWN, "DVD-SL STOP", "00"},
    {0, 0, 1000, MECHA_TASK_UI_CMD_WAIT, "CD WAIT 1s", NULL},
    {43, MECHA_CMD_TAG_ELECT_DVDSL_MIRR, 3000, MECHA_CMD_MIRR_CHECK, "DVD-SL MIRR CHECK", NULL},
    {44, MECHA_CMD_TAG_ELECT_DVDSL_MIRR_EEPROM_WR, 6000, MECHA_CMD_EEPROM_WRITE, "DVD-SL EEPROM WR 0x01E-3019", "001e3019"},
    {45, MECHA_CMD_TAG_ELECT_DVDSL_MIRR_EEPROM_WR, 6000, MECHA_CMD_EEPROM_WRITE, "DVD-SL EEPROM WR 0x01F-3039", "001f3039"},
    {46, MECHA_CMD_TAG_ELECT_DVDSL_FOCUS_OFFSET, 6000, MECHA_CMD_FE_OFFSET, "DVD-SL FE OFFSET CHECK", "0500"},
    {0, 0, 100, MECHA_TASK_UI_CMD_WAIT, "DVD-SL FE DE-FOCUS CHECK WAIT 100ms", NULL},
    {47, MECHA_CMD_TAG_ELECT_DVDSL_DEFOCUS_OFFSET, 6000, MECHA_CMD_EEPROM_READ, "DVD-SL FE DE-FOCUS CHECK", "004c"},
    {48, MECHA_CMD_TAG_ELECT_DVDSL_FB_OFFSET, 6000, MECHA_CMD_EEPROM_READ, "DVD-SL FE DE-FOCUS CHECK", "0057"},
    {49, 0, 3000, MECHA_CMD_SLED_POS_HOME, "DVD-SL SLED HOME POSITION", NULL},
    {50, 0, 6000, MECHA_CMD_TRAY, "DVD-SL FIN (TRAY OPEN)", "01"},
    {0, 0, 0, MECHA_TASK_UI_CMD_MSG, "Insert test DVD-DL and press ENTER", NULL},
    {51, 0, 6000, MECHA_CMD_TRAY, "DVD-DL TRAY CLOSE", "00"},
    {52, 0, 3000, MECHA_CMD_SLED_POS_HOME, "DVD-DL SLED HOME POSITION", NULL},
    {53, MECHA_CMD_TAG_ELECT_DVDDL_DISC_DET_JUDGE, 5000, MECHA_CMD_DISC_DETECT, "DVD-DL DETECT JUDGEMENT", NULL},
    {54, 0, 1000, MECHA_CMD_DISC_MODE_DVDDL_12, "DISC MODE DVD-DL 12cm", NULL},
    {55, 0, 40000, MECHA_CMD_AUTO_ADJ_ST_12, "DVD-DL AUTO ADJUSTMENT (1+2)", "01"},
    {0, 0, 100, MECHA_TASK_UI_CMD_WAIT, "DVD-DL AUTO ADJUSTMENT WAIT 100ms", NULL},
    {56, MECHA_CMD_TAG_ELECT_DVDDL_L0_RFDC_LEVEL, 3000, MECHA_CMD_RFDC_LEVEL, "DVD-DL-L0 GET RF DC LEVEL", NULL},
    {57, MECHA_CMD_TAG_ELECT_DVDDL_L0_FE_LOOP_GAIN, 3000, MECHA_CMD_GAIN, "DVD-DL-L0 GET FE LOOP GAIN", "13"},
    {58, MECHA_CMD_TAG_ELECT_DVDDL_L0_TE_LOOP_GAIN, 3000, MECHA_CMD_GAIN, "DVD-DL-L0 GET TE LOOP GAIN", "23"},
    {59, MECHA_CMD_TAG_ELECT_DVDDL_L0_JITTER_256_RTY, 3000, MECHA_CMD_JITTER, "DVD-DL-L0 GET JITTER (256)_WITH_RETRY", "01"},
    {60, MECHA_CMD_TAG_ELECT_DVD_SET_DSP_JITTER, 3000, MECHA_CMD_SET_DSP, "DVD-DL-L0 SET-DSP FOR JITTER (256)", "d6d80000"},
    {61, MECHA_CMD_TAG_ELECT_DVDDL_L0_JITTER_256, 3000, MECHA_CMD_JITTER, "DVD-DL-L0 GET JITTER (256)", "01"},
    {62, 0, 3000, MECHA_CMD_SET_DSP, "DVD-DL-L0 RESET-DSP FOR JITTER (256)", "d6de0000"},
    {63, 0, 3000, MECHA_CMD_FOCUS_JUMP_NEW, "DVD-DL FOCUS JUMP", "0003f00001"},
    {64, MECHA_CMD_TAG_ELECT_DVDDL_L1_RFDC_LEVEL, 3000, MECHA_CMD_RFDC_LEVEL, "DVD-DL-L1 GET RF DC LEVEL", NULL},
    {65, MECHA_CMD_TAG_ELECT_DVDDL_L1_FE_LOOP_GAIN, 3000, MECHA_CMD_GAIN, "DVD-DL-L1 GET FE LOOP GAIN", "13"},
    {66, MECHA_CMD_TAG_ELECT_DVDDL_L1_TE_LOOP_GAIN, 3000, MECHA_CMD_GAIN, "DVD-DL-L1 GET TE LOOP GAIN", "23"},
    {67, MECHA_CMD_TAG_ELECT_DVDDL_L1_JITTER_256_RTY, 3000, MECHA_CMD_JITTER, "DVD-DL-L1 GET JITTER (256)_WITH_RETRY", "01"},
    {68, MECHA_CMD_TAG_ELECT_DVD_SET_DSP_JITTER, 3000, MECHA_CMD_SET_DSP, "DVD-DL-L1 SET-DSP FOR JITTER (256)", "d6d80000"},
    {69, MECHA_CMD_TAG_ELECT_DVDDL_L1_JITTER_256, 3000, MECHA_CMD_JITTER, "DVD-DL-L1 GET JITTER (256)", "01"},
    {70, 0, 3000, MECHA_CMD_SET_DSP, "DVD-DL-L1 RESET-DSP FOR JITTER (256)", "d6de0000"},
    {71, 0, 3000, MECHA_CMD_FOCUS_UPDOWN, "DVD-DL STOP", "00"},
    {72, 0, 3000, MECHA_CMD_WRITE_CHECKSUM, "ALL EEPROM CHECK SUM WR", "00"},
    {0, 0, 100, MECHA_TASK_UI_CMD_WAIT, "CHECKSUM WAIT 100ms", NULL},
    {73, MECHA_CMD_TAG_ELECT_EEPROM_CHECKSUM_CHK, 3000, MECHA_CMD_READ_CHECKSUM, "ALL EEPROM CHECK SUM CHK", "00"},
    {74, 0, 3000, MECHA_CMD_SLED_POS_HOME, "DVD-DL SLED HOME POSITION", NULL},
    {75, 0, 6000, MECHA_CMD_TRAY, "DVD-DL FIN (TRAY OPEN)", "01"},
    {0, 0, 0, MECHA_TASK_UI_CMD_MSG, "Remove disc and press ENTER", NULL},
    {76, 0, 6000, MECHA_CMD_TRAY, "TRAY CLOSE", "00"},
    {77, 0, 3000, MECHA_CMD_SLED_POS_HOME, "FIN (SLED HOME)", NULL},
    {-1, -1, -1, -1, NULL, NULL}};

static int ElectJudgeOPTypeError(const char *result, int len)
{
    int study, OPMismatched;
    unsigned short int minthreshold, maxthreshold;
    const char *key;

    switch (ConType)
    {
        case MECHA_TYPE_F:
            if (!pstrincmp(&result[1], "0002", 4))
            {
                study = (unsigned int)strtoul(&result[5], NULL, 16);

                if (ConOP == MECHA_OP_SONY)
                {
                    minthreshold = 600;
                    maxthreshold = 1600;
                }
                else if (ConOP == MECHA_OP_SANYO)
                {
                    minthreshold = 750;
                    maxthreshold = 1800;
                }
                else
                {
                    PlatShowEMessage("Optical Block Type (F): unsupported OP.\n");
                    return 1;
                }

                CDstudy = study * (5.0f / 3.0f);
                PlatDPrintf("CDmin(d)=%d CDstudy(d)=%d CDmax(d)=%d CDdet(f)=%.0f", minthreshold, study, maxthreshold, CDstudy);
                OPMismatched = (minthreshold >= CDstudy || maxthreshold <= CDstudy);
            }
            else
            {
                PlatShowEMessage("Optical Block Type (F): unrecognized data.\n");
                return 1;
            }
            break;
        case MECHA_TYPE_G:
        case MECHA_TYPE_G2:
        case MECHA_TYPE_40:
            key = (ConType == MECHA_TYPE_40) ? "0034" : "0003";
            if (!pstrincmp(&result[1], key, 4))
            {
                study = (unsigned int)strtoul(&result[5], NULL, 16);

                if (ConOP == MECHA_OP_SONY)
                {
                    minthreshold = 660;
                    maxthreshold = 1760;
                }
                else if (ConOP == MECHA_OP_SANYO)
                {
                    minthreshold = 825;
                    maxthreshold = 1980;
                }
                else
                {
                    PlatShowEMessage("Optical Block Type (G/H): unsupported OP.\n");
                    return 1;
                }

                CDstudy = study * (2.0f / 3.0f);
                PlatDPrintf("CDmin(d)=%d CDstudy(d)=%d CDmax(d)=%d CDdet(f)=%.0f", minthreshold, study, maxthreshold, CDstudy);
                OPMismatched = (minthreshold >= CDstudy || maxthreshold <= CDstudy);
            }
            else
            {
                PlatShowEMessage("Optical Block Type (G/H): unrecognized data.\n");
                return 1;
            }
            break;
        default:
            OPMismatched = 0;
    }

    if (OPMismatched)
    {
        PlatShowEMessage("NG: Adjusting for a %s OP, but a %s OP may be installed.\n", ConOP == MECHA_OP_SONY ? "SONY" : "SANYO", ConOP == MECHA_OP_SONY ? "SANYO" : "SONY");
    }
    else
    {
        PlatDPrintf("Optical Block Type (%s) OK.\n", ConOP == MECHA_OP_SONY ? "SONY" : "SANYO");
    }

    return OPMismatched;
}

static int ElectJudgeCDFELoopGain(const char *result, int len)
{
    unsigned int value;

    value = (unsigned int)strtoul(&result[1], NULL, 16);
    if (value >= 0x08 && value <= 0x60)
    {
        PlatDPrintf("CD FE LOOP GAIN OK: %d\n", value);
        return 0;
    }
    else
    {
        PlatShowEMessage("CD FE LOOP GAIN NG: %d\n", value);
        return 1;
    }
}

static int ElectJudgeCDTELoopGain(const char *result, int len)
{
    int value;

    value = (unsigned int)strtoul(&result[1], NULL, 16);
    if (value >= 0x10 && value <= 0x60)
    {
        PlatDPrintf("CD TE LOOP GAIN OK: %d\n", value);
        return 0;
    }
    else
    {
        PlatShowEMessage("CD TE LOOP GAIN NG: %d\n", value);
        return 1;
    }
}

static int ElectJudgeDiscDetectRatio(const char *result, int len)
{
    const char *key;
    float ratio;
    unsigned int max;

    key = (ConType == MECHA_TYPE_40) ? "0034" : "0003";
    if (!pstrincmp(&result[1], key, 4))
    {
        DVDmax = max = (unsigned int)strtoul(&result[5], NULL, 16);
        switch (ConType)
        {
            case MECHA_TYPE_F:
                DVDRatio = ratio = (float)(max * 3) / (DVDmin * 7);
                if (ratio >= 1.8f)
                {
                    PlatDPrintf("CD/DVD DiscDetect Ratio OK: %f\n", ratio);
                    return 0;
                }
                else
                {
                    PlatShowEMessage("CD/DVD DiscDetect Ratio NG: %f\n", ratio);
                    return 1;
                }
            case MECHA_TYPE_G:
            case MECHA_TYPE_G2:
            case MECHA_TYPE_40:
                DVDRatio = ratio = (float)max / (DVDmin * 3);
                if (ratio >= 1.73f)
                {
                    PlatDPrintf("CD/DVD DiscDetect Ratio OK: %f\n", ratio);
                    return 0;
                }
                else
                {
                    PlatShowEMessage("CD/DVD DiscDetect Ratio NG: %f\n", ratio);
                    return 1;
                }
            default:
                PlatShowEMessage("CD/DVD DiscDetect Ratio NG: Unsupported chassis.\n");
                return 1;
        }
    }
    else
    {
        PlatShowEMessage("CD/DVD DiscDetect Ratio NG: unrecognized data.\n");
        return 1;
    }
}

static int ElectJudgeGetDVDminAndCalc(const char *result, int len)
{
    const char *key;
    unsigned int min;

    key = (ConType == MECHA_TYPE_40) ? "0035" : "0004";
    if (!pstrincmp(&result[1], key, 4))
    {
        min = (unsigned int)strtoul(&result[5], NULL, 16);
        switch (ConType)
        {
            case MECHA_TYPE_F:
                DVDmaxCalc = (unsigned short int)(min * 1.45f * (5.0f / 3.0f) + 0.5f);
                CDminCalc  = DVDmaxCalc + 1;
                DVDmin     = min;
                return 0;
            case MECHA_TYPE_G:
            case MECHA_TYPE_G2:
            case MECHA_TYPE_40:
                DVDmin = min;
                return 0;
            default:
                PlatShowEMessage("JudgeGetDVDminAndCalc: Unsupported chassis.\n");
                return 0;
        }
    }
    else
    {
        PlatShowEMessage("JudgeGetDVDminAndCalc: unrecognized data.\n");
        return 1;
    }
}

static int ElectJudgeDVDSLFELoopGain(const char *result, int len)
{
    unsigned int value;

    value = (unsigned int)strtoul(&result[1], NULL, 16);
    if (value >= 0x08 && value <= 0x60)
    {
        PlatDPrintf("DVD-SL FE LOOP GAIN OK: %d\n", value);
        return 0;
    }
    else
    {
        PlatShowEMessage("DVD-SL FE LOOP GAIN NG: %d\n", value);
        return 1;
    }
}

static int ElectJudgeDVDSLTELoopGain(const char *result, int len)
{
    unsigned int value;

    value = (unsigned int)strtoul(&result[1], NULL, 16);
    if (value >= 0x10 && value <= 0x60)
    {
        PlatDPrintf("DVD-SL TE LOOP GAIN OK: %d\n", value);
        return 0;
    }
    else
    {
        PlatShowEMessage("DVD-SL TE LOOP GAIN NG: %d\n", value);
        return 1;
    }
}

static int ElectJudgeDVDSLJitter256(const char *result, int len)
{
    unsigned int value;
    unsigned short int threshold;

    switch (ConType)
    {
        case MECHA_TYPE_G:
        case MECHA_TYPE_G2:
        case MECHA_TYPE_40:
            threshold = ConCEXDEX ? 0x3E00 : 0x2970;
            break;
        default:
            threshold = ConCEXDEX ? 0x1B00 : (ElectConIsT10K ? 0x1000 : 0x1400);
            break;
    }

    value = (unsigned int)strtoul(&result[1], NULL, 16);
    if (value <= threshold)
    {
        PlatDPrintf("DVD-SL jitter(256) OK: %d\n", value);
        return 0;
    }
    else
    {
        PlatShowEMessage("DVD-SL jitter(256) NG: %d\n", value);
        return 1;
    }
}

static int ElectJudgeDVDSLPIPOCC(const char *result, int len)
{
    unsigned int value;

    value = (unsigned int)strtoul(&result[1], NULL, 16);
    if (value <= 100)
    {
        PlatDPrintf("DVD-SL PI+PO-CC OK: %d\n", value);
        return 0;
    }
    else
    {
        PlatShowEMessage("DVD-SL PI+PO-CC NG: %d\n", value);
        return 1;
    }
}

static int ElectJudgeDVDSLPONCC(const char *result, int len)
{
    unsigned int value;

    value = (unsigned int)strtoul(&result[1], NULL, 16);
    if (value == 0)
    {
        PlatDPrintf("DVD-SL PO-NCC OK: %d\n", value);
        return 0;
    }
    else
    {
        PlatShowEMessage("DVD-SL PO-NCC NG: %d\n", value);
        return 1;
    }
}

static int ElectJudgeDVDDLDiscDetect(const char *result, int len)
{
    unsigned int value;

    value = (unsigned int)strtoul(&result[1], NULL, 16);
    if (value == DISC_TYPE_DVDD12)
    {
        PlatDPrintf("DVD-DL DISC DETECT OK: %d\n", value);
        return 0;
    }
    else
    {
        PlatShowEMessage("DVD-DL DISC DETECT NG: %d\n", value);
        return 1;
    }
}

static int ElectJudgeDVDDLL0FELoopGain(const char *result, int len)
{
    unsigned int value;

    value = (unsigned int)strtoul(&result[1], NULL, 16);
    if (value >= 0x08 && value <= 0x60)
    {
        PlatDPrintf("DVD-DL-L0 FE LOOP GAIN OK: %d\n", value);
        return 0;
    }
    else
    {
        PlatShowEMessage("DVD-DL-L0 FE LOOP GAIN NG: %d\n", value);
        return 1;
    }
}

static int ElectJudgeDVDDLL0TELoopGain(const char *result, int len)
{
    unsigned int value;

    value = (unsigned int)strtoul(&result[1], NULL, 16);
    if (value >= 0x10 && value <= 0x60)
    {
        PlatDPrintf("DVD-DL-L0 TE LOOP GAIN OK: %d\n", value);
        return 0;
    }
    else
    {
        PlatShowEMessage("DVD-DL-L0 TE LOOP GAIN NG: %d\n", value);
        return 1;
    }
}

static int ElectJudgeDVDDLL0Jitter256(const char *result, int len)
{
    unsigned int value;
    unsigned short int threshold;

    switch (ConType)
    {
        case MECHA_TYPE_G:
        case MECHA_TYPE_G2:
        case MECHA_TYPE_40:
            threshold = ConCEXDEX ? 0x4C00 : 0x2D00;
            break;
        default:
            threshold = ConCEXDEX ? 0x2300 : 0x1200;
            break;
    }

    value = (unsigned int)strtoul(&result[1], NULL, 16);
    if (value <= threshold)
    {
        PlatDPrintf("DVD-DL-L0 jitter(256) OK: %d\n", value);
        return 0;
    }
    else
    {
        PlatShowEMessage("DVD-DL-L0 jitter(256) NG: %d\n", value);
        return 1;
    }
}

static int ElectJudgeDVDDLL1FELoopGain(const char *result, int len)
{
    unsigned int value;

    value = (unsigned int)strtoul(&result[1], NULL, 16);
    if (value >= 0x08 && value <= 0x60)
    {
        PlatDPrintf("DVD-DL-L1 FE LOOP GAIN OK: %d\n", value);
        return 0;
    }
    else
    {
        PlatShowEMessage("DVD-DL-L1 FE LOOP GAIN NG: %d\n", value);
        return 1;
    }
}

static int ElectJudgeDVDDLL1TELoopGain(const char *result, int len)
{
    unsigned int value;

    value = (unsigned int)strtoul(&result[1], NULL, 16);
    if (value >= 0x10 && value <= 0x60)
    {
        PlatDPrintf("DVD-DL-L1 TE LOOP GAIN OK: %d\n", value);
        return 0;
    }
    else
    {
        PlatShowEMessage("DVD-DL-L1 TE LOOP GAIN NG: %d\n", value);
        return 1;
    }
}

static int ElectJudgeDVDDLL1Jitter256(const char *result, int len)
{
    unsigned int value;
    unsigned short int threshold;

    switch (ConType)
    {
        case MECHA_TYPE_G:
        case MECHA_TYPE_G2:
        case MECHA_TYPE_40:
            threshold = ConCEXDEX ? 0x4C00 : 0x2D00;
            break;
        default:
            threshold = ConCEXDEX ? 0x2300 : 0x1200;
            break;
    }

    value = (unsigned int)strtoul(&result[1], NULL, 16);
    if (value <= threshold)
    {
        PlatDPrintf("DVD-DL-L1 jitter(256) OK: %d\n", value);
        return 0;
    }
    else
    {
        PlatShowEMessage("DVD-DL-L1 jitter(256) NG: %d\n", value);
        return 1;
    }
}

static int ElectJudgeChecksum(const char *result, int len)
{
    unsigned int value;

    value = (unsigned int)strtoul(&result[1], NULL, 16);
    if (value == 0)
    {
        PlatDPrintf("EEPROM checksum OK: %d\n", value);
        return 0;
    }
    else
    {
        PlatShowEMessage("EEPROM checksum NG: %d\n", value);
        return 1;
    }
}

static int ElectJudgeFCSSearchData(const char *data, int len)
{
    char number[5];
    unsigned int value, divisor, result;

    if (len == 9)
    {
        strncpy(number, &data[1], 4);
        number[4] = '\0';
        divisor   = (unsigned int)strtoul(number, NULL, 16);
        value     = (unsigned int)strtoul(&data[5], NULL, 16);
        result    = value * 100 / divisor - 100;

        if (result >= -10 && result <= 10)
        {
            PlatDPrintf("FCS Search Data OK: %d\n", result);
            return 0;
        }
        else
        {
            PlatShowEMessage("FCS Search Data NG: %d\n", result);
            return 1;
        }
    }
    else
    {
        PlatShowEMessage("FCS Search Data NG: data length wrong (!=8)\n");
        return 1;
    }
}

static int ElectJudgeDVDSL_MIRR(const char *result, int len)
{
    unsigned int value;

    value = (unsigned int)strtoul(&result[1], NULL, 16);
    switch (value)
    {
        case 0x00:
        case 0xFF:
            DisableEEPMIRRWrite = 1;
            return 0;
        case 0x01:
            DisableEEPMIRRWrite = 0;
            return 0;
        default:
            PlatShowEMessage("DVD-SL MIRR: Unknown data on PCEA1055\n");
            return 1;
    }
}

static int ElectJudgeDVDSLJitter256WithRetry(const char *result, int len)
{
    int value;

    value = (int)strtoul(&result[1], NULL, 16);
    if (value <= (ConCEXDEX ? 0x3E00 : 0x2970))
    {
        Enable2ndJitter256Check = 0;
        PlatDPrintf("DVD-SL jitter(256)_WITH_RETRY OK: %d\n", value);
    }
    else
    {
        Enable2ndJitter256Check = 1;
        PlatShowEMessage("DVD-SL jitter(256)_WITH_RETRY NG: %d\n", value);
    }

    // As odd as how this seems, this was done in the SONY tool.
    Enable2ndJitter256Check = 1;

    return 0;
}

static int ElectJudgeDVDDLL0Jitter256WithRetry(const char *result, int len)
{
    int value;

    value = (int)strtoul(&result[1], NULL, 16);
    if (value <= (ConCEXDEX ? 0x4C00 : 0x2D00))
    {
        Enable2ndJitter256Check = 0;
        PlatDPrintf("DVD-DL-L0 jitter(256)_WITH_RETRY OK: %d\n", value);
    }
    else
    {
        Enable2ndJitter256Check = 1;
        PlatShowEMessage("DVD-DL-L0 jitter(256)_WITH_RETRY NG: %d\n", value);
    }

    // As odd as how this seems, this was done in the SONY tool.
    Enable2ndJitter256Check = 1;

    return 0;
}

static int ElectJudgeDVDDLL1Jitter256WithRetry(const char *result, int len)
{
    int value;

    value = (int)strtoul(&result[1], NULL, 16);
    if (value <= (ConCEXDEX ? 0x4C00 : 0x2D00))
    {
        Enable2ndJitter256Check = 0;
        PlatDPrintf("DVD-DL-L0 jitter(256)_WITH_RETRY OK: %d\n", value);
    }
    else
    {
        Enable2ndJitter256Check = 1;
        PlatShowEMessage("DVD-DL-L0 jitter(256)_WITH_RETRY NG: %d\n", value);
    }

    // As odd as how this seems, this was done in the SONY tool.
    Enable2ndJitter256Check = 1;

    return 0;
}

static int ElectDiscDetectPullIn(const char *result, int len)
{
    unsigned short int value;

    value              = (unsigned short int)strtoul(&result[5], NULL, 16);
    DiscDetectValue136 = (u16)((value - 90.0f) * 1.6f);
    return 0;
}

static int ElectJudgeCDRFDCLevel(const char *data, int len)
{
    char number[3];
    unsigned short int value, value2;
    int result;

    strncpy(number, &data[1], 2);
    number[2] = '\0';
    value     = (unsigned short int)strtoul(number, NULL, 16);
    value2    = (unsigned short int)strtoul(&data[3], NULL, 16);
    result    = value - value2;

    if (result >= 0x49 && result <= 0x89)
    {
        PlatDPrintf("CD RFDC level OK: %d\n", result);
        return 0;
    }
    else
    {
        PlatShowEMessage("CD RFDC level NG: %d\n", result);
        return 1;
    }
}

static int ElectJudgeDVDSLRFDCLevel(const char *data, int len)
{
    char number[3];
    unsigned short int value, value2;
    int result;

    strncpy(number, &data[1], 2);
    number[2] = '\0';
    value     = (unsigned short int)strtoul(number, NULL, 16);
    value2    = (unsigned short int)strtoul(&data[3], NULL, 16);
    result    = value - value2;

    if (result >= 0x35)
    {
        PlatDPrintf("DVD-SL RFDC level OK: %d\n", result);
        return 0;
    }
    else
    {
        PlatShowEMessage("DVD-SL RFDC level NG: %d\n", result);
        return 1;
    }
}

static int ElectJudgeDVDDLL0RFDCLevel(const char *data, int len)
{
    char number[3];
    unsigned short int value, value2;
    int result;

    strncpy(number, &data[1], 2);
    number[2] = '\0';
    value     = (unsigned short int)strtoul(number, NULL, 16);
    value2    = (unsigned short int)strtoul(&data[3], NULL, 16);
    result    = value - value2;

    if (result >= 0x35)
    {
        PlatDPrintf("DVD-DL-L0 RFDC level OK: %d\n", result);
        return 0;
    }
    else
    {
        PlatShowEMessage("DVD-DL-L0 RFDC level NG: %d\n", result);
        return 1;
    }
}

static int ElectJudgeDVDDLL1RFDCLevel(const char *data, int len)
{
    char number[3];
    unsigned short int value, value2;
    int result;

    strncpy(number, &data[1], 2);
    number[2] = '\0';
    value     = (unsigned short int)strtoul(number, NULL, 16);
    value2    = (unsigned short int)strtoul(&data[3], NULL, 16);
    result    = value - value2;

    if (result >= 0x35)
    {
        PlatDPrintf("DVD-DL-L1 RFDC level OK: %d\n, result");
        return 0;
    }
    else
    {
        PlatShowEMessage("DVD-DL-L1 RFDC level NG: %d\n, result");
        return 1;
    }
}

static int ElectJudgeCDTPP(const char *data, int len)
{
    char number[3];
    unsigned short int value1, value2, value3;
    int sub32, Tbal;

    number[2] = '\0';
    strncpy(number, &data[1], 2);
    value1 = (unsigned short int)strtoul(number, NULL, 16);
    strncpy(number, &data[3], 2);
    value2 = (unsigned short int)strtoul(number, NULL, 16);
    value3 = (unsigned short int)strtoul(&data[5], NULL, 16);
    value1 -= value2;

    if (value1 >= 0x35 && value1 <= 0x7E) // TPP check
    {
        PlatDPrintf("CD TPP OK: %d\n", value1);
        // Tbal check
        sub32 = value3 - value2;
        Tbal  = (int)((value1 * 0.5f - sub32) / value1 * 100);

        if (Tbal >= -30 && Tbal <= 30)
        {
            PlatDPrintf("CD TPP Tbal  OK: %ld\n", Tbal);
            return 0;
        }
        else
        {
            PlatShowEMessage("CD TPP Tbal NG: %ld\n", Tbal);
            return 1;
        }
    }
    else
    {
        PlatShowEMessage("CD TPP NG: %d\n", value1);
        return 1;
    }
}

static int JudgeDVDSLFocusOffset(const char *data, int len)
{
    unsigned short int value2, value3, value6;
    char value[3];
    float min, max, offset;

    value[2] = '\0';
    strncpy(value, &data[3], 2);
    value2 = (unsigned short int)strtoul(value, NULL, 16);
    strncpy(value, &data[5], 2);
    value3 = (unsigned short int)strtoul(value, NULL, 16);
    strncpy(value, &data[11], 2);
    value6         = (unsigned short int)strtoul(value, NULL, 16);

    ConFocusOffset = value2 - value3;
    min            = 0.0f;
    max            = 0.0f;
    if (ConOP == MECHA_OP_SONY)
    {
        min = -12.5;
        max = 17.5;
    }
    else if (ConOP == MECHA_OP_SANYO)
    {
        min = -15.0;
        max = 15.0;
    }

    offset = (ConFocusOffset * 0.5f - (value6 - value3)) / ConFocusOffset * 100;

    if (min <= offset && offset <= max)
    {
        PlatDPrintf("DVD-SL FOCUS OFFSET Check OK: %f\n", offset);
        return 0;
    }
    else
    {
        PlatShowEMessage("DVD-SL FOCUS OFFSET Check NG: %f\n", offset);
        return 1;
    }
}

static int JudgeDVDSLDeFocusOffset(const char *data, int len)
{
    unsigned int offset;
    float result;

    offset = (unsigned int)strtoul(&data[5], NULL, 16);
    if (offset == 0x100)
        offset = -(~offset & 0xFF);
    else
        offset &= 0xFF;

    result = offset / (ConFocusOffset << 2) * 100.0f;

    if (result >= -16.0f && result <= 16.0f)
    {
        PlatDPrintf("DVD-SL DE-FOCUS OFFSET Check OK: %f\n", result);
        return 0;
    }
    else
    {
        PlatShowEMessage("DVD-SL DE-FOCUS OFFSET Check NG: %f\n", result);
        return 1;
    }
}

static int JudgeDVDSLFBOffset(const char *data, int len)
{
    char number[3];
    unsigned short int FbOffsetHi, FbOffsetLo;

    strncpy(number, &data[5], 2);
    number[2]  = '\0';
    FbOffsetHi = (unsigned short int)strtoul(number, NULL, 16);
    FbOffsetLo = (unsigned short int)strtoul(&data[7], NULL, 16);

    if ((FbOffsetHi <= 0x4C) || (FbOffsetHi >= 0xB4 && FbOffsetHi <= 0xFF))
    {
        PlatDPrintf("DVD-SL FB OFFSET (HI) OK: %d\n", FbOffsetHi);

        if ((FbOffsetLo <= 0x4C) || (FbOffsetLo >= 0xB4 && FbOffsetLo <= 0xFF))
        {
            PlatDPrintf("DVD-SL FB OFFSET (LO) Check OK: %d\n", FbOffsetLo);
            return 0;
        }
        else
        {
            PlatShowEMessage("DVD-SL FB OFFSET (LO) Check NG: %d\n", FbOffsetLo);
            return 1;
        }
    }
    else
    {
        PlatShowEMessage("DVD-SL FB OFFSET (HI) NG: %d\n", FbOffsetHi);
        return 1;
    }
}

static int ElectTxHandler(MechaTask_t *task)
{
    switch (task->tag)
    {
        case MECHA_CMD_TAG_ELECT_CD_TYPE:
            if (ElectConIsT10K)
            {
                task->command = MECHA_CMD_DISC_MODE_CD_12;
                task->label   = "DISC MODE CD 12cm";
            }
            return 0;
        case MECHA_CMD_TAG_ELECT_DVDSL_WR_WORK0_F0:
            if (DisableDVDDLAdjWorkaround)
            { // Disable the next 4 commands
                task[0].id      = MECHA_TASK_ID_UI;
                task[0].tag     = 0;
                task[0].command = MECHA_TASK_UI_CMD_SKIP;
                task[1].id      = MECHA_TASK_ID_UI;
                task[1].tag     = 0;
                task[1].command = MECHA_TASK_UI_CMD_SKIP;
                task[2].id      = MECHA_TASK_ID_UI;
                task[2].tag     = 0;
                task[2].command = MECHA_TASK_UI_CMD_SKIP;
                task[3].id      = MECHA_TASK_ID_UI;
                task[3].tag     = 0;
                task[3].command = MECHA_TASK_UI_CMD_SKIP;
            }
            return 0;
        case MECHA_CMD_TAG_ELECT_DVDSL_WR_WORK0_NEW:
            sprintf(&task->args[7], "%04x", DiscDetectValue136);
            return 0;
        case MECHA_CMD_TAG_ELECT_DISC_DET_CDMIN_WR:
            sprintf(&task->args[7], "%04x", CDminCalc);
            return 0;
        case MECHA_CMD_TAG_ELECT_DISC_DET_DVDMAX_WR:
            sprintf(&task->args[7], "%04x", DVDmaxCalc);
            return 0;
        case MECHA_CMD_TAG_ELECT_DVDSL_MIRR_EEPROM_WR:
            if (DisableEEPMIRRWrite)
            {
                task->id      = MECHA_TASK_ID_UI;
                task->tag     = 0;
                task->command = MECHA_TASK_UI_CMD_SKIP;
            }
            return 0;
        case MECHA_CMD_TAG_ELECT_DEX_NEWLENS:
            if (ConCEXDEX || ConLens != MECHA_LENS_T609K)
            {
                task->id      = MECHA_TASK_ID_UI;
                task->tag     = 0;
                task->command = MECHA_TASK_UI_CMD_SKIP;
            }
            return 0;
        case MECHA_CMD_TAG_ELECT_DVD_SET_DSP_JITTER:
            if (!Enable2ndJitter256Check)
            { // Disable the next 2 commands
                task[0].id      = MECHA_TASK_ID_UI;
                task[0].tag     = 0;
                task[0].command = MECHA_TASK_UI_CMD_SKIP;
                task[1].id      = MECHA_TASK_ID_UI;
                task[1].tag     = 0;
                task[1].command = MECHA_TASK_UI_CMD_SKIP;
            }
            return 0;
        default:
            return 0;
    }
}

static int ElectRxHandler(MechaTask_t *task, const char *result, short int len)
{
    switch (result[0])
    {
        case '0': // Rx-OK
            switch (task->tag)
            {
                case MECHA_CMD_TAG_ELECT_CD_FE_LOOP_GAIN:
                    return ElectJudgeCDFELoopGain(result, len);
                case MECHA_CMD_TAG_ELECT_CD_TE_LOOP_GAIN:
                    return ElectJudgeCDTELoopGain(result, len);
                case MECHA_CMD_TAG_ELECT_OP_TYPE_ERROR:
                    return ElectJudgeOPTypeError(result, len);
                case MECHA_CMD_TAG_ELECT_CD_FCS_CHECK:
                    return ElectJudgeFCSSearchData(result, len);
                case MECHA_CMD_TAG_ELECT_CD_RFDC_LEVEL:
                    return ElectJudgeCDRFDCLevel(result, len);
                case MECHA_CMD_TAG_ELECT_CD_TPP:
                    return ElectJudgeCDTPP(result, len);
                case MECHA_CMD_TAG_ELECT_DVDSL_DETECT_ADJ:
                    DisableDVDDLAdjWorkaround = 1;
                    return 0;
                case MECHA_CMD_TAG_ELECT_DVDSL_RD_PULL_IN:
                    return ElectDiscDetectPullIn(result, len);
                case MECHA_CMD_TAG_ELECT_DISC_DET_DVDMIN_RD:
                    return ElectJudgeGetDVDminAndCalc(result, len);
                case MECHA_CMD_TAG_ELECT_DVDSL_FE_LOOP_GAIN:
                    return ElectJudgeDVDSLFELoopGain(result, len);
                case MECHA_CMD_TAG_ELECT_DVDSL_TE_LOOP_GAIN:
                    return ElectJudgeDVDSLTELoopGain(result, len);
                case MECHA_CMD_TAG_ELECT_DVDSL_JITTER_256:
                    return ElectJudgeDVDSLJitter256(result, len);
                case MECHA_CMD_TAG_ELECT_DVDSL_JITTER_256_RTY:
                    return ElectJudgeDVDSLJitter256WithRetry(result, len);
                case MECHA_CMD_TAG_ELECT_DVDSL_PIPOCC_RATE:
                    return ElectJudgeDVDSLPIPOCC(result, len);
                case MECHA_CMD_TAG_ELECT_DVDSL_PONCC_RATE:
                    return ElectJudgeDVDSLPONCC(result, len);
                case MECHA_CMD_TAG_ELECT_DVDSL_MIRR:
                    return ElectJudgeDVDSL_MIRR(result, len);
                case MECHA_CMD_TAG_ELECT_DVDSL_DISC_DET_JUDGE:
                    return ElectJudgeDiscDetectRatio(result, len);
                case MECHA_CMD_TAG_ELECT_DVDSL_RFDC_LEVEL:
                    return ElectJudgeDVDSLRFDCLevel(result, len);
                case MECHA_CMD_TAG_ELECT_DVDSL_FOCUS_OFFSET:
                    return JudgeDVDSLFocusOffset(result, len);
                case MECHA_CMD_TAG_ELECT_DVDSL_DEFOCUS_OFFSET:
                    return JudgeDVDSLDeFocusOffset(result, len);
                case MECHA_CMD_TAG_ELECT_DVDSL_FB_OFFSET:
                    return JudgeDVDSLFBOffset(result, len);
                case MECHA_CMD_TAG_ELECT_DVDDL_DISC_DET_JUDGE:
                    return ElectJudgeDVDDLDiscDetect(result, len);
                case MECHA_CMD_TAG_ELECT_DVDDL_L0_FE_LOOP_GAIN:
                    return ElectJudgeDVDDLL0FELoopGain(result, len);
                case MECHA_CMD_TAG_ELECT_DVDDL_L0_TE_LOOP_GAIN:
                    return ElectJudgeDVDDLL0TELoopGain(result, len);
                case MECHA_CMD_TAG_ELECT_DVDDL_L0_JITTER_256:
                    return ElectJudgeDVDDLL0Jitter256(result, len);
                case MECHA_CMD_TAG_ELECT_DVDDL_L0_JITTER_256_RTY:
                    return ElectJudgeDVDDLL0Jitter256WithRetry(result, len);
                case MECHA_CMD_TAG_ELECT_DVDDL_L0_RFDC_LEVEL:
                    return ElectJudgeDVDDLL0RFDCLevel(result, len);
                case MECHA_CMD_TAG_ELECT_DVDDL_L1_FE_LOOP_GAIN:
                    return ElectJudgeDVDDLL1FELoopGain(result, len);
                case MECHA_CMD_TAG_ELECT_DVDDL_L1_TE_LOOP_GAIN:
                    return ElectJudgeDVDDLL1TELoopGain(result, len);
                case MECHA_CMD_TAG_ELECT_DVDDL_L1_JITTER_256:
                    return ElectJudgeDVDDLL1Jitter256(result, len);
                case MECHA_CMD_TAG_ELECT_DVDDL_L1_JITTER_256_RTY:
                    return ElectJudgeDVDDLL1Jitter256WithRetry(result, len);
                case MECHA_CMD_TAG_ELECT_DVDDL_L1_RFDC_LEVEL:
                    return ElectJudgeDVDDLL1RFDCLevel(result, len);
                case MECHA_CMD_TAG_ELECT_EEPROM_CHECKSUM_CHK:
                    return ElectJudgeChecksum(result, len);
                default:
                    return 0;
            }
            break;
        case '1': // Rx-NGErr
            switch (task->tag)
            {
                case MECHA_CMD_TAG_ELECT_DVDSL_DETECT_ADJ:
                    DisableDVDDLAdjWorkaround = 0;
                    return 0;
                default:
                    return MechaDefaultHandleRes1(task, result, len);
            }
            break;
        case '2': // Rx-NGBadCmd
            switch (task->tag)
            {
                default:
                    return MechaDefaultHandleRes2(task, result, len);
            }
        default:
            return MechaDefaultHandleResUnknown(task, result, len);
    }
}

int ElectAutoAdjust(void)
{
    int result;
    const ElectMechaTaskPrep_t *cmd;

    switch (ConType)
    {
        case MECHA_TYPE_36:
        case MECHA_TYPE_38:
            cmd = AutoAdjACommands;
            break;
        case MECHA_TYPE_39:
            cmd = AutoAdj139Commands;
            break;
        case MECHA_TYPE_F:
            cmd = AutoAdjFCommands;
            break;
        case MECHA_TYPE_G:
            cmd = AutoAdjGCommands;
            break;
        case MECHA_TYPE_G2:
            cmd = AutoAdjG2Commands;
            break;
        case MECHA_TYPE_40:
            cmd = AutoAdj140Commands;
            break;
        default:
            PlatShowEMessage("ELECT: Unsupported MECHACON.\n");
            return EINVAL;
    }

    PlatDPrintf("\n--- AUTO ELECT ADJUSTMENT START ---\n"
                "MECHA type: %d\n\n",
                ConType);

    for (result = 0; cmd->id != 0xFF; cmd++)
    {
        if ((result = MechaCommandAdd(cmd->command, cmd->args, cmd->id, cmd->tag, cmd->timeout, cmd->label)) != 0)
            break;
    }

    if (result == 0)
    {
        result = MechaCommandExecuteList(&ElectTxHandler, &ElectRxHandler);
    }
    else
        MechaCommandListClear();

    PlatDPrintf("\nAdjustment result: %d\n"
                "--- AUTO ELECT ADJUSTMENT FIN ---\n",
                result);

    return result;
}
